bootstrap.servers=redpanda:9092
group.id=seev-analytics-connect
config.storage.topic=seev.analytics.connect.config
offset.storage.topic=seev.analytics.connect.offsets
status.storage.topic=seev.analytics.connect.status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
plugin.path=/kafka/connect,/kafka/connect/plugins
rest.port=8083
heartbeat.interval.ms=10000
