{{- $root := . }}
{{- range $name, $spec := .Values.services }}
{{- if $spec.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" $root.Values.global.serviceAccountPrefix $name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $root.Values.global.appNamespace }}
  labels:
    {{- include "seev.labels" $root | nindent 4 }}
  {{ with $spec.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
automountServiceAccountToken: false
---
{{- end }}
{{- end }}
