// Code generated by MockGen. DO NOT EDIT.
// Source: account_repository.go
//
// Generated by this command:
//
//	mockgen -source=account_repository.go -destination=account_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// GetAccountCurrency mocks base method.
func (m *MockAccountRepository) GetAccountCurrency(ctx context.Context, accountID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountCurrency", ctx, accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountCurrency indicates an expected call of GetAccountCurrency.
func (mr *MockAccountRepositoryMockRecorder) GetAccountCurrency(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountCurrency", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountCurrency), ctx, accountID)
}

// GetAccountID mocks base method.
func (m *MockAccountRepository) GetAccountID(ctx context.Context, userID uuid.UUID, accountType string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountID", ctx, userID, accountType)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountID indicates an expected call of GetAccountID.
func (mr *MockAccountRepositoryMockRecorder) GetAccountID(ctx, userID, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountID", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountID), ctx, userID, accountType)
}

// GetOwnerID mocks base method.
func (m *MockAccountRepository) GetOwnerID(ctx context.Context, accountID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerID", ctx, accountID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerID indicates an expected call of GetOwnerID.
func (mr *MockAccountRepositoryMockRecorder) GetOwnerID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerID", reflect.TypeOf((*MockAccountRepository)(nil).GetOwnerID), ctx, accountID)
}

// GetPocketAccountID mocks base method.
func (m *MockAccountRepository) GetPocketAccountID(ctx context.Context, userID uuid.UUID, pocketCode string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPocketAccountID", ctx, userID, pocketCode)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPocketAccountID indicates an expected call of GetPocketAccountID.
func (mr *MockAccountRepositoryMockRecorder) GetPocketAccountID(ctx, userID, pocketCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPocketAccountID", reflect.TypeOf((*MockAccountRepository)(nil).GetPocketAccountID), ctx, userID, pocketCode)
}

// GetSystemAccountID mocks base method.
func (m *MockAccountRepository) GetSystemAccountID(ctx context.Context, accountType, qualifier, currency string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemAccountID", ctx, accountType, qualifier, currency)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemAccountID indicates an expected call of GetSystemAccountID.
func (mr *MockAccountRepositoryMockRecorder) GetSystemAccountID(ctx, accountType, qualifier, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemAccountID", reflect.TypeOf((*MockAccountRepository)(nil).GetSystemAccountID), ctx, accountType, qualifier, currency)
}

// ListByOwner mocks base method.
func (m *MockAccountRepository) ListByOwner(ctx context.Context, userID uuid.UUID) ([]model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ctx, userID)
	ret0, _ := ret[0].([]model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockAccountRepositoryMockRecorder) ListByOwner(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockAccountRepository)(nil).ListByOwner), ctx, userID)
}
