// Code generated by MockGen. DO NOT EDIT.
// Source: account_balance_repository.go
//
// Generated by this command:
//
//	mockgen -source=account_balance_repository.go -destination=account_balance_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// ApplySystemDeltas mocks base method.
func (m *MockBalanceRepository) ApplySystemDeltas(ctx context.Context, tx *sql.Tx, deltas map[uuid.UUID]decimal.Decimal) (map[uuid.UUID]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySystemDeltas", ctx, tx, deltas)
	ret0, _ := ret[0].(map[uuid.UUID]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplySystemDeltas indicates an expected call of ApplySystemDeltas.
func (mr *MockBalanceRepositoryMockRecorder) ApplySystemDeltas(ctx, tx, deltas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySystemDeltas", reflect.TypeOf((*MockBalanceRepository)(nil).ApplySystemDeltas), ctx, tx, deltas)
}

// GetAccountFlags mocks base method.
func (m *MockBalanceRepository) GetAccountFlags(ctx context.Context, tx *sql.Tx, ids []uuid.UUID) (map[uuid.UUID]model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountFlags", ctx, tx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountFlags indicates an expected call of GetAccountFlags.
func (mr *MockBalanceRepositoryMockRecorder) GetAccountFlags(ctx, tx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountFlags", reflect.TypeOf((*MockBalanceRepository)(nil).GetAccountFlags), ctx, tx, ids)
}

// GetBalance mocks base method.
func (m *MockBalanceRepository) GetBalance(ctx context.Context, accountID uuid.UUID) (model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceRepositoryMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceRepository)(nil).GetBalance), ctx, accountID)
}

// LockBalances mocks base method.
func (m *MockBalanceRepository) LockBalances(ctx context.Context, tx *sql.Tx, accountIDs []uuid.UUID) (map[uuid.UUID]model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBalances", ctx, tx, accountIDs)
	ret0, _ := ret[0].(map[uuid.UUID]model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockBalances indicates an expected call of LockBalances.
func (mr *MockBalanceRepositoryMockRecorder) LockBalances(ctx, tx, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBalances", reflect.TypeOf((*MockBalanceRepository)(nil).LockBalances), ctx, tx, accountIDs)
}

// UpdateBalances mocks base method.
func (m *MockBalanceRepository) UpdateBalances(ctx context.Context, tx *sql.Tx, newBalances map[uuid.UUID]decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalances", ctx, tx, newBalances)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalances indicates an expected call of UpdateBalances.
func (mr *MockBalanceRepositoryMockRecorder) UpdateBalances(ctx, tx, newBalances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalances", reflect.TypeOf((*MockBalanceRepository)(nil).UpdateBalances), ctx, tx, newBalances)
}
