// Code generated by MockGen. DO NOT EDIT.
// Source: chargeback_dispute_repository.go
//
// Generated by this command:
//
//	mockgen -source=chargeback_dispute_repository.go -destination=chargeback_dispute_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChargebackDisputeRepository is a mock of ChargebackDisputeRepository interface.
type MockChargebackDisputeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChargebackDisputeRepositoryMockRecorder
	isgomock struct{}
}

// MockChargebackDisputeRepositoryMockRecorder is the mock recorder for MockChargebackDisputeRepository.
type MockChargebackDisputeRepositoryMockRecorder struct {
	mock *MockChargebackDisputeRepository
}

// NewMockChargebackDisputeRepository creates a new mock instance.
func NewMockChargebackDisputeRepository(ctrl *gomock.Controller) *MockChargebackDisputeRepository {
	mock := &MockChargebackDisputeRepository{ctrl: ctrl}
	mock.recorder = &MockChargebackDisputeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChargebackDisputeRepository) EXPECT() *MockChargebackDisputeRepositoryMockRecorder {
	return m.recorder
}

// CreateDispute mocks base method.
func (m *MockChargebackDisputeRepository) CreateDispute(ctx context.Context, d model.ChargebackDispute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDispute", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDispute indicates an expected call of CreateDispute.
func (mr *MockChargebackDisputeRepositoryMockRecorder) CreateDispute(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDispute", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).CreateDispute), ctx, d)
}

// GetDispute mocks base method.
func (m *MockChargebackDisputeRepository) GetDispute(ctx context.Context, id uuid.UUID) (model.ChargebackDispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDispute", ctx, id)
	ret0, _ := ret[0].(model.ChargebackDispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDispute indicates an expected call of GetDispute.
func (mr *MockChargebackDisputeRepositoryMockRecorder) GetDispute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDispute", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).GetDispute), ctx, id)
}

// GetDisputeByRef mocks base method.
func (m *MockChargebackDisputeRepository) GetDisputeByRef(ctx context.Context, disputeRef string) (model.ChargebackDispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisputeByRef", ctx, disputeRef)
	ret0, _ := ret[0].(model.ChargebackDispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisputeByRef indicates an expected call of GetDisputeByRef.
func (mr *MockChargebackDisputeRepositoryMockRecorder) GetDisputeByRef(ctx, disputeRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisputeByRef", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).GetDisputeByRef), ctx, disputeRef)
}

// LinkChargebackTx mocks base method.
func (m *MockChargebackDisputeRepository) LinkChargebackTx(ctx context.Context, id, chargebackTxID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkChargebackTx", ctx, id, chargebackTxID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkChargebackTx indicates an expected call of LinkChargebackTx.
func (mr *MockChargebackDisputeRepositoryMockRecorder) LinkChargebackTx(ctx, id, chargebackTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkChargebackTx", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).LinkChargebackTx), ctx, id, chargebackTxID)
}

// ListDisputesByOriginalTx mocks base method.
func (m *MockChargebackDisputeRepository) ListDisputesByOriginalTx(ctx context.Context, originalTxID uuid.UUID) ([]model.ChargebackDispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDisputesByOriginalTx", ctx, originalTxID)
	ret0, _ := ret[0].([]model.ChargebackDispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDisputesByOriginalTx indicates an expected call of ListDisputesByOriginalTx.
func (mr *MockChargebackDisputeRepositoryMockRecorder) ListDisputesByOriginalTx(ctx, originalTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDisputesByOriginalTx", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).ListDisputesByOriginalTx), ctx, originalTxID)
}

// ListOpenDisputes mocks base method.
func (m *MockChargebackDisputeRepository) ListOpenDisputes(ctx context.Context, limit, offset int) ([]model.ChargebackDispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenDisputes", ctx, limit, offset)
	ret0, _ := ret[0].([]model.ChargebackDispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenDisputes indicates an expected call of ListOpenDisputes.
func (mr *MockChargebackDisputeRepositoryMockRecorder) ListOpenDisputes(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenDisputes", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).ListOpenDisputes), ctx, limit, offset)
}

// ListStatusChanges mocks base method.
func (m *MockChargebackDisputeRepository) ListStatusChanges(ctx context.Context, disputeID uuid.UUID) ([]model.ChargebackDisputeStatusChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStatusChanges", ctx, disputeID)
	ret0, _ := ret[0].([]model.ChargebackDisputeStatusChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStatusChanges indicates an expected call of ListStatusChanges.
func (mr *MockChargebackDisputeRepositoryMockRecorder) ListStatusChanges(ctx, disputeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStatusChanges", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).ListStatusChanges), ctx, disputeID)
}

// ResolveDispute mocks base method.
func (m *MockChargebackDisputeRepository) ResolveDispute(ctx context.Context, id uuid.UUID, status, resolvedBy, reason string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDispute", ctx, id, status, resolvedBy, reason)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDispute indicates an expected call of ResolveDispute.
func (mr *MockChargebackDisputeRepositoryMockRecorder) ResolveDispute(ctx, id, status, resolvedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDispute", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).ResolveDispute), ctx, id, status, resolvedBy, reason)
}

// SubmitEvidence mocks base method.
func (m *MockChargebackDisputeRepository) SubmitEvidence(ctx context.Context, id uuid.UUID, evidenceRef, changedBy string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitEvidence", ctx, id, evidenceRef, changedBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitEvidence indicates an expected call of SubmitEvidence.
func (mr *MockChargebackDisputeRepositoryMockRecorder) SubmitEvidence(ctx, id, evidenceRef, changedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitEvidence", reflect.TypeOf((*MockChargebackDisputeRepository)(nil).SubmitEvidence), ctx, id, evidenceRef, changedBy)
}
