// Code generated by MockGen. DO NOT EDIT.
// Source: disbursement_repository.go
//
// Generated by this command:
//
//	mockgen -source=disbursement_repository.go -destination=disbursement_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDisbursementRepository is a mock of DisbursementRepository interface.
type MockDisbursementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDisbursementRepositoryMockRecorder
	isgomock struct{}
}

// MockDisbursementRepositoryMockRecorder is the mock recorder for MockDisbursementRepository.
type MockDisbursementRepositoryMockRecorder struct {
	mock *MockDisbursementRepository
}

// NewMockDisbursementRepository creates a new mock instance.
func NewMockDisbursementRepository(ctrl *gomock.Controller) *MockDisbursementRepository {
	mock := &MockDisbursementRepository{ctrl: ctrl}
	mock.recorder = &MockDisbursementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisbursementRepository) EXPECT() *MockDisbursementRepositoryMockRecorder {
	return m.recorder
}

// CreateBatchWithItems mocks base method.
func (m *MockDisbursementRepository) CreateBatchWithItems(ctx context.Context, tx *sql.Tx, batch model.DisbursementBatch, items []model.DisbursementItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithItems", ctx, tx, batch, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithItems indicates an expected call of CreateBatchWithItems.
func (mr *MockDisbursementRepositoryMockRecorder) CreateBatchWithItems(ctx, tx, batch, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithItems", reflect.TypeOf((*MockDisbursementRepository)(nil).CreateBatchWithItems), ctx, tx, batch, items)
}

// GetBatch mocks base method.
func (m *MockDisbursementRepository) GetBatch(ctx context.Context, id uuid.UUID) (model.DisbursementBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx, id)
	ret0, _ := ret[0].(model.DisbursementBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockDisbursementRepositoryMockRecorder) GetBatch(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockDisbursementRepository)(nil).GetBatch), ctx, id)
}

// GetCounts mocks base method.
func (m *MockDisbursementRepository) GetCounts(ctx context.Context, batchID uuid.UUID) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounts", ctx, batchID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounts indicates an expected call of GetCounts.
func (mr *MockDisbursementRepositoryMockRecorder) GetCounts(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounts", reflect.TypeOf((*MockDisbursementRepository)(nil).GetCounts), ctx, batchID)
}

// ListItems mocks base method.
func (m *MockDisbursementRepository) ListItems(ctx context.Context, batchID uuid.UUID, status string, limit, offset int) ([]model.DisbursementItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, batchID, status, limit, offset)
	ret0, _ := ret[0].([]model.DisbursementItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockDisbursementRepositoryMockRecorder) ListItems(ctx, batchID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockDisbursementRepository)(nil).ListItems), ctx, batchID, status, limit, offset)
}

// ListItemsToProcess mocks base method.
func (m *MockDisbursementRepository) ListItemsToProcess(ctx context.Context, batchID uuid.UUID, includeFailed bool, limit int) ([]model.DisbursementItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsToProcess", ctx, batchID, includeFailed, limit)
	ret0, _ := ret[0].([]model.DisbursementItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsToProcess indicates an expected call of ListItemsToProcess.
func (mr *MockDisbursementRepositoryMockRecorder) ListItemsToProcess(ctx, batchID, includeFailed, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsToProcess", reflect.TypeOf((*MockDisbursementRepository)(nil).ListItemsToProcess), ctx, batchID, includeFailed, limit)
}

// MarkItemFailed mocks base method.
func (m *MockDisbursementRepository) MarkItemFailed(ctx context.Context, tx *sql.Tx, itemID uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkItemFailed", ctx, tx, itemID, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkItemFailed indicates an expected call of MarkItemFailed.
func (mr *MockDisbursementRepositoryMockRecorder) MarkItemFailed(ctx, tx, itemID, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkItemFailed", reflect.TypeOf((*MockDisbursementRepository)(nil).MarkItemFailed), ctx, tx, itemID, errMsg)
}

// MarkItemPosted mocks base method.
func (m *MockDisbursementRepository) MarkItemPosted(ctx context.Context, tx *sql.Tx, itemID, txID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkItemPosted", ctx, tx, itemID, txID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkItemPosted indicates an expected call of MarkItemPosted.
func (mr *MockDisbursementRepositoryMockRecorder) MarkItemPosted(ctx, tx, itemID, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkItemPosted", reflect.TypeOf((*MockDisbursementRepository)(nil).MarkItemPosted), ctx, tx, itemID, txID)
}

// UpdateBatchStatus mocks base method.
func (m *MockDisbursementRepository) UpdateBatchStatus(ctx context.Context, tx *sql.Tx, batchID uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchStatus", ctx, tx, batchID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchStatus indicates an expected call of UpdateBatchStatus.
func (mr *MockDisbursementRepositoryMockRecorder) UpdateBatchStatus(ctx, tx, batchID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchStatus", reflect.TypeOf((*MockDisbursementRepository)(nil).UpdateBatchStatus), ctx, tx, batchID, status)
}
