// Code generated by MockGen. DO NOT EDIT.
// Source: fee_repository.go
//
// Generated by this command:
//
//	mockgen -source=fee_repository.go -destination=fee_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryRower is a mock of QueryRower interface.
type MockQueryRower struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRowerMockRecorder
	isgomock struct{}
}

// MockQueryRowerMockRecorder is the mock recorder for MockQueryRower.
type MockQueryRowerMockRecorder struct {
	mock *MockQueryRower
}

// NewMockQueryRower creates a new mock instance.
func NewMockQueryRower(ctrl *gomock.Controller) *MockQueryRower {
	mock := &MockQueryRower{ctrl: ctrl}
	mock.recorder = &MockQueryRowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRower) EXPECT() *MockQueryRowerMockRecorder {
	return m.recorder
}

// QueryRowContext mocks base method.
func (m *MockQueryRower) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockQueryRowerMockRecorder) QueryRowContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockQueryRower)(nil).QueryRowContext), varargs...)
}

// MockFeeRepository is a mock of FeeRepository interface.
type MockFeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeeRepositoryMockRecorder
	isgomock struct{}
}

// MockFeeRepositoryMockRecorder is the mock recorder for MockFeeRepository.
type MockFeeRepositoryMockRecorder struct {
	mock *MockFeeRepository
}

// NewMockFeeRepository creates a new mock instance.
func NewMockFeeRepository(ctrl *gomock.Controller) *MockFeeRepository {
	mock := &MockFeeRepository{ctrl: ctrl}
	mock.recorder = &MockFeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeRepository) EXPECT() *MockFeeRepositoryMockRecorder {
	return m.recorder
}

// CreateRule mocks base method.
func (m *MockFeeRepository) CreateRule(ctx context.Context, rule model.FeeRule) (model.FeeRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule)
	ret0, _ := ret[0].(model.FeeRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockFeeRepositoryMockRecorder) CreateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockFeeRepository)(nil).CreateRule), ctx, rule)
}

// GetQuote mocks base method.
func (m *MockFeeRepository) GetQuote(ctx context.Context, quoteID, userID uuid.UUID) (decimal.Decimal, decimal.Decimal, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuote", ctx, quoteID, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(decimal.Decimal)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetQuote indicates an expected call of GetQuote.
func (mr *MockFeeRepositoryMockRecorder) GetQuote(ctx, quoteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuote", reflect.TypeOf((*MockFeeRepository)(nil).GetQuote), ctx, quoteID, userID)
}

// InsertQuote mocks base method.
func (m *MockFeeRepository) InsertQuote(ctx context.Context, q model.FeeQuote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertQuote", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertQuote indicates an expected call of InsertQuote.
func (mr *MockFeeRepositoryMockRecorder) InsertQuote(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertQuote", reflect.TypeOf((*MockFeeRepository)(nil).InsertQuote), ctx, q)
}

// ListRules mocks base method.
func (m *MockFeeRepository) ListRules(ctx context.Context) ([]model.FeeRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]model.FeeRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockFeeRepositoryMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockFeeRepository)(nil).ListRules), ctx)
}

// QuoteExists mocks base method.
func (m *MockFeeRepository) QuoteExists(ctx context.Context, exec QueryRower, quoteID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteExists", ctx, exec, quoteID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuoteExists indicates an expected call of QuoteExists.
func (mr *MockFeeRepositoryMockRecorder) QuoteExists(ctx, exec, quoteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteExists", reflect.TypeOf((*MockFeeRepository)(nil).QuoteExists), ctx, exec, quoteID, userID)
}

// ResolveRule mocks base method.
func (m *MockFeeRepository) ResolveRule(ctx context.Context, txType, currency string, userID uuid.UUID, gateway string) (int64, int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRule", ctx, txType, currency, userID, gateway)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ResolveRule indicates an expected call of ResolveRule.
func (mr *MockFeeRepositoryMockRecorder) ResolveRule(ctx, txType, currency, userID, gateway any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRule", reflect.TypeOf((*MockFeeRepository)(nil).ResolveRule), ctx, txType, currency, userID, gateway)
}

// TryConsumeQuote mocks base method.
func (m *MockFeeRepository) TryConsumeQuote(ctx context.Context, exec QueryRower, quoteID, userID uuid.UUID, txType, currency string, amount decimal.Decimal, ref string) (decimal.Decimal, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryConsumeQuote", ctx, exec, quoteID, userID, txType, currency, amount, ref)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryConsumeQuote indicates an expected call of TryConsumeQuote.
func (mr *MockFeeRepositoryMockRecorder) TryConsumeQuote(ctx, exec, quoteID, userID, txType, currency, amount, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryConsumeQuote", reflect.TypeOf((*MockFeeRepository)(nil).TryConsumeQuote), ctx, exec, quoteID, userID, txType, currency, amount, ref)
}

// UpdateRule mocks base method.
func (m *MockFeeRepository) UpdateRule(ctx context.Context, rule model.FeeRule) (model.FeeRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, rule)
	ret0, _ := ret[0].(model.FeeRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockFeeRepositoryMockRecorder) UpdateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockFeeRepository)(nil).UpdateRule), ctx, rule)
}
