// Code generated by MockGen. DO NOT EDIT.
// Source: ledger_entry_repository.go
//
// Generated by this command:
//
//	mockgen -source=ledger_entry_repository.go -destination=ledger_entry_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// InsertEntries mocks base method.
func (m *MockEntryRepository) InsertEntries(ctx context.Context, tx *sql.Tx, txID uuid.UUID, entries []model.EntryInstruction, newBalances map[uuid.UUID]decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntries", ctx, tx, txID, entries, newBalances)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEntries indicates an expected call of InsertEntries.
func (mr *MockEntryRepositoryMockRecorder) InsertEntries(ctx, tx, txID, entries, newBalances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntries", reflect.TypeOf((*MockEntryRepository)(nil).InsertEntries), ctx, tx, txID, entries, newBalances)
}

// ListByAccount mocks base method.
func (m *MockEntryRepository) ListByAccount(ctx context.Context, accountID uuid.UUID, beforeCreatedAt time.Time, beforeID uuid.UUID, limit int) ([]model.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID, beforeCreatedAt, beforeID, limit)
	ret0, _ := ret[0].([]model.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockEntryRepositoryMockRecorder) ListByAccount(ctx, accountID, beforeCreatedAt, beforeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockEntryRepository)(nil).ListByAccount), ctx, accountID, beforeCreatedAt, beforeID, limit)
}

// ListByAccountRange mocks base method.
func (m *MockEntryRepository) ListByAccountRange(ctx context.Context, accountID uuid.UUID, from, to time.Time, loc *time.Location, limit int) ([]model.StatementEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountRange", ctx, accountID, from, to, loc, limit)
	ret0, _ := ret[0].([]model.StatementEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountRange indicates an expected call of ListByAccountRange.
func (mr *MockEntryRepositoryMockRecorder) ListByAccountRange(ctx, accountID, from, to, loc, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountRange", reflect.TypeOf((*MockEntryRepository)(nil).ListByAccountRange), ctx, accountID, from, to, loc, limit)
}
