// Code generated by MockGen. DO NOT EDIT.
// Source: ledger_transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=ledger_transaction_repository.go -destination=ledger_transaction_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// CloseOriginal mocks base method.
func (m *MockTransactionRepository) CloseOriginal(ctx context.Context, tx *sql.Tx, originalID, byTxID uuid.UUID, reason string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseOriginal", ctx, tx, originalID, byTxID, reason)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseOriginal indicates an expected call of CloseOriginal.
func (mr *MockTransactionRepositoryMockRecorder) CloseOriginal(ctx, tx, originalID, byTxID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseOriginal", reflect.TypeOf((*MockTransactionRepository)(nil).CloseOriginal), ctx, tx, originalID, byTxID, reason)
}

// GetAccountIDs mocks base method.
func (m *MockTransactionRepository) GetAccountIDs(ctx context.Context, transactionID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIDs", ctx, transactionID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIDs indicates an expected call of GetAccountIDs.
func (mr *MockTransactionRepositoryMockRecorder) GetAccountIDs(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIDs", reflect.TypeOf((*MockTransactionRepository)(nil).GetAccountIDs), ctx, transactionID)
}

// GetByID mocks base method.
func (m *MockTransactionRepository) GetByID(ctx context.Context, transactionID uuid.UUID) (model.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, transactionID)
	ret0, _ := ret[0].(model.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionRepositoryMockRecorder) GetByID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByID), ctx, transactionID)
}

// GetByIdempotencyKey mocks base method.
func (m *MockTransactionRepository) GetByIdempotencyKey(ctx context.Context, key string, scope *string) (model.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key, scope)
	ret0, _ := ret[0].(model.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockTransactionRepositoryMockRecorder) GetByIdempotencyKey(ctx, key, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockTransactionRepository)(nil).GetByIdempotencyKey), ctx, key, scope)
}

// GetEntries mocks base method.
func (m *MockTransactionRepository) GetEntries(ctx context.Context, tx *sql.Tx, transactionID uuid.UUID) ([]model.LedgerEntryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntries", ctx, tx, transactionID)
	ret0, _ := ret[0].([]model.LedgerEntryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntries indicates an expected call of GetEntries.
func (mr *MockTransactionRepositoryMockRecorder) GetEntries(ctx, tx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntries", reflect.TypeOf((*MockTransactionRepository)(nil).GetEntries), ctx, tx, transactionID)
}

// GetHeader mocks base method.
func (m *MockTransactionRepository) GetHeader(ctx context.Context, tx *sql.Tx, transactionID uuid.UUID) (string, string, decimal.Decimal, *uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", ctx, tx, transactionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(decimal.Decimal)
	ret3, _ := ret[3].(*uuid.UUID)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockTransactionRepositoryMockRecorder) GetHeader(ctx, tx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockTransactionRepository)(nil).GetHeader), ctx, tx, transactionID)
}

// GetStatus mocks base method.
func (m *MockTransactionRepository) GetStatus(ctx context.Context, tx *sql.Tx, transactionID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, tx, transactionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockTransactionRepositoryMockRecorder) GetStatus(ctx, tx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockTransactionRepository)(nil).GetStatus), ctx, tx, transactionID)
}

// GetStatusByIdempotency mocks base method.
func (m *MockTransactionRepository) GetStatusByIdempotency(ctx context.Context, tx *sql.Tx, key string, scope *string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusByIdempotency", ctx, tx, key, scope)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusByIdempotency indicates an expected call of GetStatusByIdempotency.
func (mr *MockTransactionRepositoryMockRecorder) GetStatusByIdempotency(ctx, tx, key, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusByIdempotency", reflect.TypeOf((*MockTransactionRepository)(nil).GetStatusByIdempotency), ctx, tx, key, scope)
}

// Insert mocks base method.
func (m *MockTransactionRepository) Insert(ctx context.Context, tx *sql.Tx, params InsertTransactionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTransactionRepositoryMockRecorder) Insert(ctx, tx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTransactionRepository)(nil).Insert), ctx, tx, params)
}

// UpdateStatus mocks base method.
func (m *MockTransactionRepository) UpdateStatus(ctx context.Context, tx *sql.Tx, transactionID uuid.UUID, status string, errorMessage *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, transactionID, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTransactionRepositoryMockRecorder) UpdateStatus(ctx, tx, transactionID, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateStatus), ctx, tx, transactionID, status, errorMessage)
}
