// Code generated by MockGen. DO NOT EDIT.
// Source: outbox_event_repository.go
//
// Generated by this command:
//
//	mockgen -source=outbox_event_repository.go -destination=outbox_event_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// ClaimFailedForRetry mocks base method.
func (m *MockOutboxRepository) ClaimFailedForRetry(ctx context.Context, limit int) ([]model.OutboxEventRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimFailedForRetry", ctx, limit)
	ret0, _ := ret[0].([]model.OutboxEventRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimFailedForRetry indicates an expected call of ClaimFailedForRetry.
func (mr *MockOutboxRepositoryMockRecorder) ClaimFailedForRetry(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimFailedForRetry", reflect.TypeOf((*MockOutboxRepository)(nil).ClaimFailedForRetry), ctx, limit)
}

// ClaimPending mocks base method.
func (m *MockOutboxRepository) ClaimPending(ctx context.Context, limit int) ([]model.OutboxEventRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPending", ctx, limit)
	ret0, _ := ret[0].([]model.OutboxEventRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPending indicates an expected call of ClaimPending.
func (mr *MockOutboxRepositoryMockRecorder) ClaimPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPending", reflect.TypeOf((*MockOutboxRepository)(nil).ClaimPending), ctx, limit)
}

// CountByStatuses mocks base method.
func (m *MockOutboxRepository) CountByStatuses(ctx context.Context, statuses []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatuses", ctx, statuses)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatuses indicates an expected call of CountByStatuses.
func (mr *MockOutboxRepositoryMockRecorder) CountByStatuses(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatuses", reflect.TypeOf((*MockOutboxRepository)(nil).CountByStatuses), ctx, statuses)
}

// CountPending mocks base method.
func (m *MockOutboxRepository) CountPending(ctx context.Context) (int, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPending", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountPending indicates an expected call of CountPending.
func (mr *MockOutboxRepositoryMockRecorder) CountPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPending", reflect.TypeOf((*MockOutboxRepository)(nil).CountPending), ctx)
}

// InsertEvents mocks base method.
func (m *MockOutboxRepository) InsertEvents(ctx context.Context, tx *sql.Tx, events []model.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvents", ctx, tx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvents indicates an expected call of InsertEvents.
func (mr *MockOutboxRepositoryMockRecorder) InsertEvents(ctx, tx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvents", reflect.TypeOf((*MockOutboxRepository)(nil).InsertEvents), ctx, tx, events)
}

// ListDead mocks base method.
func (m *MockOutboxRepository) ListDead(ctx context.Context, limit, offset int) ([]model.DeadOutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDead", ctx, limit, offset)
	ret0, _ := ret[0].([]model.DeadOutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDead indicates an expected call of ListDead.
func (mr *MockOutboxRepositoryMockRecorder) ListDead(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDead", reflect.TypeOf((*MockOutboxRepository)(nil).ListDead), ctx, limit, offset)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, id uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, id, errMsg)
}

// MarkPublished mocks base method.
func (m *MockOutboxRepository) MarkPublished(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkPublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkPublished), ctx, id)
}

// ReapStuck mocks base method.
func (m *MockOutboxRepository) ReapStuck(ctx context.Context, olderThan time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReapStuck", ctx, olderThan)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReapStuck indicates an expected call of ReapStuck.
func (mr *MockOutboxRepositoryMockRecorder) ReapStuck(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReapStuck", reflect.TypeOf((*MockOutboxRepository)(nil).ReapStuck), ctx, olderThan)
}

// ReplayAllDead mocks base method.
func (m *MockOutboxRepository) ReplayAllDead(ctx context.Context, olderThan time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayAllDead", ctx, olderThan)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayAllDead indicates an expected call of ReplayAllDead.
func (mr *MockOutboxRepositoryMockRecorder) ReplayAllDead(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayAllDead", reflect.TypeOf((*MockOutboxRepository)(nil).ReplayAllDead), ctx, olderThan)
}

// ReplayDead mocks base method.
func (m *MockOutboxRepository) ReplayDead(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDead", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplayDead indicates an expected call of ReplayDead.
func (mr *MockOutboxRepositoryMockRecorder) ReplayDead(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDead", reflect.TypeOf((*MockOutboxRepository)(nil).ReplayDead), ctx, id)
}
