// Code generated by MockGen. DO NOT EDIT.
// Source: pending_adjustment_repository.go
//
// Generated by this command:
//
//	mockgen -source=pending_adjustment_repository.go -destination=pending_adjustment_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingAdjustmentRepository is a mock of PendingAdjustmentRepository interface.
type MockPendingAdjustmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPendingAdjustmentRepositoryMockRecorder
	isgomock struct{}
}

// MockPendingAdjustmentRepositoryMockRecorder is the mock recorder for MockPendingAdjustmentRepository.
type MockPendingAdjustmentRepositoryMockRecorder struct {
	mock *MockPendingAdjustmentRepository
}

// NewMockPendingAdjustmentRepository creates a new mock instance.
func NewMockPendingAdjustmentRepository(ctrl *gomock.Controller) *MockPendingAdjustmentRepository {
	mock := &MockPendingAdjustmentRepository{ctrl: ctrl}
	mock.recorder = &MockPendingAdjustmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingAdjustmentRepository) EXPECT() *MockPendingAdjustmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPendingAdjustmentRepository) Create(ctx context.Context, tx *sql.Tx, id uuid.UUID, requestedBy string, cmdPayload []byte, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, id, requestedBy, cmdPayload, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) Create(ctx, tx, id, requestedBy, cmdPayload, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).Create), ctx, tx, id, requestedBy, cmdPayload, reason)
}

// GetByID mocks base method.
func (m *MockPendingAdjustmentRepository) GetByID(ctx context.Context, id uuid.UUID) (model.PendingAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.PendingAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPendingAdjustmentRepository) List(ctx context.Context, status string, limit int) ([]model.PendingAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, status, limit)
	ret0, _ := ret[0].([]model.PendingAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) List(ctx, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).List), ctx, status, limit)
}

// MarkApproved mocks base method.
func (m *MockPendingAdjustmentRepository) MarkApproved(ctx context.Context, tx *sql.Tx, id uuid.UUID, approvedBy string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkApproved", ctx, tx, id, approvedBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkApproved indicates an expected call of MarkApproved.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) MarkApproved(ctx, tx, id, approvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkApproved", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).MarkApproved), ctx, tx, id, approvedBy)
}

// MarkExecuted mocks base method.
func (m *MockPendingAdjustmentRepository) MarkExecuted(ctx context.Context, tx *sql.Tx, id, executedTxID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkExecuted", ctx, tx, id, executedTxID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkExecuted indicates an expected call of MarkExecuted.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) MarkExecuted(ctx, tx, id, executedTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkExecuted", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).MarkExecuted), ctx, tx, id, executedTxID)
}

// MarkFailed mocks base method.
func (m *MockPendingAdjustmentRepository) MarkFailed(ctx context.Context, tx *sql.Tx, id uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, tx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) MarkFailed(ctx, tx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).MarkFailed), ctx, tx, id, errMsg)
}

// MarkRejected mocks base method.
func (m *MockPendingAdjustmentRepository) MarkRejected(ctx context.Context, tx *sql.Tx, id uuid.UUID, approvedBy string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRejected", ctx, tx, id, approvedBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRejected indicates an expected call of MarkRejected.
func (mr *MockPendingAdjustmentRepositoryMockRecorder) MarkRejected(ctx, tx, id, approvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRejected", reflect.TypeOf((*MockPendingAdjustmentRepository)(nil).MarkRejected), ctx, tx, id, approvedBy)
}
