// Code generated by MockGen. DO NOT EDIT.
// Source: provisioning_repository.go
//
// Generated by this command:
//
//	mockgen -source=provisioning_repository.go -destination=provisioning_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockProvisioningRepository is a mock of ProvisioningRepository interface.
type MockProvisioningRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProvisioningRepositoryMockRecorder
	isgomock struct{}
}

// MockProvisioningRepositoryMockRecorder is the mock recorder for MockProvisioningRepository.
type MockProvisioningRepositoryMockRecorder struct {
	mock *MockProvisioningRepository
}

// NewMockProvisioningRepository creates a new mock instance.
func NewMockProvisioningRepository(ctrl *gomock.Controller) *MockProvisioningRepository {
	mock := &MockProvisioningRepository{ctrl: ctrl}
	mock.recorder = &MockProvisioningRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisioningRepository) EXPECT() *MockProvisioningRepositoryMockRecorder {
	return m.recorder
}

// UpsertAccount mocks base method.
func (m *MockProvisioningRepository) UpsertAccount(ctx context.Context, tx *sql.Tx, params UpsertAccountParams) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAccount", ctx, tx, params)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAccount indicates an expected call of UpsertAccount.
func (mr *MockProvisioningRepositoryMockRecorder) UpsertAccount(ctx, tx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAccount", reflect.TypeOf((*MockProvisioningRepository)(nil).UpsertAccount), ctx, tx, params)
}
