// Code generated by MockGen. DO NOT EDIT.
// Source: recon_repository.go
//
// Generated by this command:
//
//	mockgen -source=recon_repository.go -destination=recon_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockReconRepository is a mock of ReconRepository interface.
type MockReconRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReconRepositoryMockRecorder
	isgomock struct{}
}

// MockReconRepositoryMockRecorder is the mock recorder for MockReconRepository.
type MockReconRepositoryMockRecorder struct {
	mock *MockReconRepository
}

// NewMockReconRepository creates a new mock instance.
func NewMockReconRepository(ctrl *gomock.Controller) *MockReconRepository {
	mock := &MockReconRepository{ctrl: ctrl}
	mock.recorder = &MockReconRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconRepository) EXPECT() *MockReconRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockReconRepository) CreateBatch(ctx context.Context, tx *sql.Tx, batch model.ReconBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, tx, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockReconRepositoryMockRecorder) CreateBatch(ctx, tx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockReconRepository)(nil).CreateBatch), ctx, tx, batch)
}

// GetBatch mocks base method.
func (m *MockReconRepository) GetBatch(ctx context.Context, id uuid.UUID) (model.ReconBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx, id)
	ret0, _ := ret[0].(model.ReconBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockReconRepositoryMockRecorder) GetBatch(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockReconRepository)(nil).GetBatch), ctx, id)
}

// GetCounts mocks base method.
func (m *MockReconRepository) GetCounts(ctx context.Context, batchID uuid.UUID) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounts", ctx, batchID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounts indicates an expected call of GetCounts.
func (mr *MockReconRepositoryMockRecorder) GetCounts(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounts", reflect.TypeOf((*MockReconRepository)(nil).GetCounts), ctx, batchID)
}

// GetItem mocks base method.
func (m *MockReconRepository) GetItem(ctx context.Context, id uuid.UUID) (model.ReconItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, id)
	ret0, _ := ret[0].(model.ReconItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockReconRepositoryMockRecorder) GetItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockReconRepository)(nil).GetItem), ctx, id)
}

// InsertItems mocks base method.
func (m *MockReconRepository) InsertItems(ctx context.Context, tx *sql.Tx, items []model.ReconItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertItems", ctx, tx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertItems indicates an expected call of InsertItems.
func (mr *MockReconRepositoryMockRecorder) InsertItems(ctx, tx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertItems", reflect.TypeOf((*MockReconRepository)(nil).InsertItems), ctx, tx, items)
}

// ListBatches mocks base method.
func (m *MockReconRepository) ListBatches(ctx context.Context, limit, offset int) ([]model.ReconBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBatches", ctx, limit, offset)
	ret0, _ := ret[0].([]model.ReconBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBatches indicates an expected call of ListBatches.
func (mr *MockReconRepositoryMockRecorder) ListBatches(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBatches", reflect.TypeOf((*MockReconRepository)(nil).ListBatches), ctx, limit, offset)
}

// ListItems mocks base method.
func (m *MockReconRepository) ListItems(ctx context.Context, batchID uuid.UUID, matchStatus string, limit, offset int) ([]model.ReconItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, batchID, matchStatus, limit, offset)
	ret0, _ := ret[0].([]model.ReconItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockReconRepositoryMockRecorder) ListItems(ctx, batchID, matchStatus, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockReconRepository)(nil).ListItems), ctx, batchID, matchStatus, limit, offset)
}

// MarkItemResolved mocks base method.
func (m *MockReconRepository) MarkItemResolved(ctx context.Context, tx *sql.Tx, itemID, adjustmentID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkItemResolved", ctx, tx, itemID, adjustmentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkItemResolved indicates an expected call of MarkItemResolved.
func (mr *MockReconRepositoryMockRecorder) MarkItemResolved(ctx, tx, itemID, adjustmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkItemResolved", reflect.TypeOf((*MockReconRepository)(nil).MarkItemResolved), ctx, tx, itemID, adjustmentID)
}

// RunMatcher mocks base method.
func (m *MockReconRepository) RunMatcher(ctx context.Context, tx *sql.Tx, batchID uuid.UUID, gateway string, reportDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMatcher", ctx, tx, batchID, gateway, reportDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMatcher indicates an expected call of RunMatcher.
func (mr *MockReconRepositoryMockRecorder) RunMatcher(ctx, tx, batchID, gateway, reportDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMatcher", reflect.TypeOf((*MockReconRepository)(nil).RunMatcher), ctx, tx, batchID, gateway, reportDate)
}

// UpdateBatchStatus mocks base method.
func (m *MockReconRepository) UpdateBatchStatus(ctx context.Context, tx *sql.Tx, batchID uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchStatus", ctx, tx, batchID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchStatus indicates an expected call of UpdateBatchStatus.
func (mr *MockReconRepositoryMockRecorder) UpdateBatchStatus(ctx, tx, batchID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchStatus", reflect.TypeOf((*MockReconRepository)(nil).UpdateBatchStatus), ctx, tx, batchID, status)
}

// MockrowScanner is a mock of rowScanner interface.
type MockrowScanner struct {
	ctrl     *gomock.Controller
	recorder *MockrowScannerMockRecorder
	isgomock struct{}
}

// MockrowScannerMockRecorder is the mock recorder for MockrowScanner.
type MockrowScannerMockRecorder struct {
	mock *MockrowScanner
}

// NewMockrowScanner creates a new mock instance.
func NewMockrowScanner(ctrl *gomock.Controller) *MockrowScanner {
	mock := &MockrowScanner{ctrl: ctrl}
	mock.recorder = &MockrowScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrowScanner) EXPECT() *MockrowScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockrowScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockrowScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockrowScanner)(nil).Scan), dest...)
}
