// Code generated by MockGen. DO NOT EDIT.
// Source: reporting_repository.go
//
// Generated by this command:
//
//	mockgen -source=reporting_repository.go -destination=reporting_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockReportingRepository is a mock of ReportingRepository interface.
type MockReportingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportingRepositoryMockRecorder
	isgomock struct{}
}

// MockReportingRepositoryMockRecorder is the mock recorder for MockReportingRepository.
type MockReportingRepositoryMockRecorder struct {
	mock *MockReportingRepository
}

// NewMockReportingRepository creates a new mock instance.
func NewMockReportingRepository(ctrl *gomock.Controller) *MockReportingRepository {
	mock := &MockReportingRepository{ctrl: ctrl}
	mock.recorder = &MockReportingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportingRepository) EXPECT() *MockReportingRepositoryMockRecorder {
	return m.recorder
}

// DailyMutation mocks base method.
func (m *MockReportingRepository) DailyMutation(ctx context.Context, from, to time.Time) ([]model.ReportDailyMutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyMutation", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportDailyMutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyMutation indicates an expected call of DailyMutation.
func (mr *MockReportingRepositoryMockRecorder) DailyMutation(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyMutation", reflect.TypeOf((*MockReportingRepository)(nil).DailyMutation), ctx, from, to)
}

// DailyPosition mocks base method.
func (m *MockReportingRepository) DailyPosition(ctx context.Context, from, to time.Time) ([]model.ReportDailyPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyPosition", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportDailyPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyPosition indicates an expected call of DailyPosition.
func (mr *MockReportingRepositoryMockRecorder) DailyPosition(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyPosition", reflect.TypeOf((*MockReportingRepository)(nil).DailyPosition), ctx, from, to)
}

// ReconSummary mocks base method.
func (m *MockReportingRepository) ReconSummary(ctx context.Context, from, to time.Time) ([]model.ReportReconSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconSummary", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportReconSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconSummary indicates an expected call of ReconSummary.
func (mr *MockReportingRepositoryMockRecorder) ReconSummary(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconSummary", reflect.TypeOf((*MockReportingRepository)(nil).ReconSummary), ctx, from, to)
}
