// Code generated by MockGen. DO NOT EDIT.
// Source: savings_repository.go
//
// Generated by this command:
//
//	mockgen -source=savings_repository.go -destination=savings_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSavingsRepository is a mock of SavingsRepository interface.
type MockSavingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSavingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSavingsRepositoryMockRecorder is the mock recorder for MockSavingsRepository.
type MockSavingsRepositoryMockRecorder struct {
	mock *MockSavingsRepository
}

// NewMockSavingsRepository creates a new mock instance.
func NewMockSavingsRepository(ctrl *gomock.Controller) *MockSavingsRepository {
	mock := &MockSavingsRepository{ctrl: ctrl}
	mock.recorder = &MockSavingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavingsRepository) EXPECT() *MockSavingsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSavingsRepository) Get(ctx context.Context, accountID uuid.UUID) (model.SavingsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, accountID)
	ret0, _ := ret[0].(model.SavingsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSavingsRepositoryMockRecorder) Get(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSavingsRepository)(nil).Get), ctx, accountID)
}

// ListAll mocks base method.
func (m *MockSavingsRepository) ListAll(ctx context.Context) ([]model.SavingsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]model.SavingsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockSavingsRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockSavingsRepository)(nil).ListAll), ctx)
}

// ListEnabled mocks base method.
func (m *MockSavingsRepository) ListEnabled(ctx context.Context) ([]model.SavingsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabled", ctx)
	ret0, _ := ret[0].([]model.SavingsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabled indicates an expected call of ListEnabled.
func (mr *MockSavingsRepositoryMockRecorder) ListEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabled", reflect.TypeOf((*MockSavingsRepository)(nil).ListEnabled), ctx)
}

// Upsert mocks base method.
func (m *MockSavingsRepository) Upsert(ctx context.Context, tx *sql.Tx, cfg model.SavingsConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSavingsRepositoryMockRecorder) Upsert(ctx, tx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSavingsRepository)(nil).Upsert), ctx, tx, cfg)
}
