// Code generated by MockGen. DO NOT EDIT.
// Source: scheduled_transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=scheduled_transaction_repository.go -destination=scheduled_transaction_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduledTransactionRepository is a mock of ScheduledTransactionRepository interface.
type MockScheduledTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduledTransactionRepositoryMockRecorder is the mock recorder for MockScheduledTransactionRepository.
type MockScheduledTransactionRepositoryMockRecorder struct {
	mock *MockScheduledTransactionRepository
}

// NewMockScheduledTransactionRepository creates a new mock instance.
func NewMockScheduledTransactionRepository(ctrl *gomock.Controller) *MockScheduledTransactionRepository {
	mock := &MockScheduledTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockScheduledTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledTransactionRepository) EXPECT() *MockScheduledTransactionRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockScheduledTransactionRepository) Cancel(ctx context.Context, tx *sql.Tx, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockScheduledTransactionRepositoryMockRecorder) Cancel(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).Cancel), ctx, tx, id)
}

// Create mocks base method.
func (m *MockScheduledTransactionRepository) Create(ctx context.Context, tx *sql.Tx, id, userID uuid.UUID, cmdPayload []byte, kind string, runAtDate time.Time, dayOfMonth *int, createdBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, id, userID, cmdPayload, kind, runAtDate, dayOfMonth, createdBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduledTransactionRepositoryMockRecorder) Create(ctx, tx, id, userID, cmdPayload, kind, runAtDate, dayOfMonth, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).Create), ctx, tx, id, userID, cmdPayload, kind, runAtDate, dayOfMonth, createdBy)
}

// GetByID mocks base method.
func (m *MockScheduledTransactionRepository) GetByID(ctx context.Context, id uuid.UUID) (model.ScheduledTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.ScheduledTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduledTransactionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockScheduledTransactionRepository) List(ctx context.Context, userID uuid.UUID) ([]model.ScheduledTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]model.ScheduledTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScheduledTransactionRepositoryMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).List), ctx, userID)
}

// ListDue mocks base method.
func (m *MockScheduledTransactionRepository) ListDue(ctx context.Context, asOf time.Time) ([]model.ScheduledTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDue", ctx, asOf)
	ret0, _ := ret[0].([]model.ScheduledTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDue indicates an expected call of ListDue.
func (mr *MockScheduledTransactionRepositoryMockRecorder) ListDue(ctx, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDue", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).ListDue), ctx, asOf)
}

// MarkBusinessFailure mocks base method.
func (m *MockScheduledTransactionRepository) MarkBusinessFailure(ctx context.Context, tx *sql.Tx, id uuid.UUID, errMsg string, terminal bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBusinessFailure", ctx, tx, id, errMsg, terminal)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBusinessFailure indicates an expected call of MarkBusinessFailure.
func (mr *MockScheduledTransactionRepositoryMockRecorder) MarkBusinessFailure(ctx, tx, id, errMsg, terminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBusinessFailure", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).MarkBusinessFailure), ctx, tx, id, errMsg, terminal)
}

// MarkSuccess mocks base method.
func (m *MockScheduledTransactionRepository) MarkSuccess(ctx context.Context, tx *sql.Tx, id uuid.UUID, asOf time.Time, finish bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSuccess", ctx, tx, id, asOf, finish)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSuccess indicates an expected call of MarkSuccess.
func (mr *MockScheduledTransactionRepositoryMockRecorder) MarkSuccess(ctx, tx, id, asOf, finish any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuccess", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).MarkSuccess), ctx, tx, id, asOf, finish)
}

// Pause mocks base method.
func (m *MockScheduledTransactionRepository) Pause(ctx context.Context, tx *sql.Tx, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pause indicates an expected call of Pause.
func (mr *MockScheduledTransactionRepositoryMockRecorder) Pause(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).Pause), ctx, tx, id)
}

// Resume mocks base method.
func (m *MockScheduledTransactionRepository) Resume(ctx context.Context, tx *sql.Tx, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockScheduledTransactionRepositoryMockRecorder) Resume(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockScheduledTransactionRepository)(nil).Resume), ctx, tx, id)
}
