// Code generated by MockGen. DO NOT EDIT.
// Source: verification_repository.go
//
// Generated by this command:
//
//	mockgen -source=verification_repository.go -destination=verification_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationRepository is a mock of VerificationRepository interface.
type MockVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationRepositoryMockRecorder is the mock recorder for MockVerificationRepository.
type MockVerificationRepositoryMockRecorder struct {
	mock *MockVerificationRepository
}

// NewMockVerificationRepository creates a new mock instance.
func NewMockVerificationRepository(ctrl *gomock.Controller) *MockVerificationRepository {
	mock := &MockVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationRepository) EXPECT() *MockVerificationRepositoryMockRecorder {
	return m.recorder
}

// ProjectionDiscrepancies mocks base method.
func (m *MockVerificationRepository) ProjectionDiscrepancies(ctx context.Context) ([]model.ProjectionDiscrepancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectionDiscrepancies", ctx)
	ret0, _ := ret[0].([]model.ProjectionDiscrepancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectionDiscrepancies indicates an expected call of ProjectionDiscrepancies.
func (mr *MockVerificationRepositoryMockRecorder) ProjectionDiscrepancies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectionDiscrepancies", reflect.TypeOf((*MockVerificationRepository)(nil).ProjectionDiscrepancies), ctx)
}

// TrialBalanceDiscrepancies mocks base method.
func (m *MockVerificationRepository) TrialBalanceDiscrepancies(ctx context.Context) ([]model.TrialBalanceDiscrepancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrialBalanceDiscrepancies", ctx)
	ret0, _ := ret[0].([]model.TrialBalanceDiscrepancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrialBalanceDiscrepancies indicates an expected call of TrialBalanceDiscrepancies.
func (mr *MockVerificationRepositoryMockRecorder) TrialBalanceDiscrepancies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrialBalanceDiscrepancies", reflect.TypeOf((*MockVerificationRepository)(nil).TrialBalanceDiscrepancies), ctx)
}
