// Code generated by MockGen. DO NOT EDIT.
// Source: kyc_repository.go
//
// Generated by this command:
//
//	mockgen -source=kyc_repository.go -destination=kyc_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/auth/model"
	gomock "go.uber.org/mock/gomock"
)

// MockKYCRepository is a mock of KYCRepository interface.
type MockKYCRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKYCRepositoryMockRecorder
	isgomock struct{}
}

// MockKYCRepositoryMockRecorder is the mock recorder for MockKYCRepository.
type MockKYCRepositoryMockRecorder struct {
	mock *MockKYCRepository
}

// NewMockKYCRepository creates a new mock instance.
func NewMockKYCRepository(ctrl *gomock.Controller) *MockKYCRepository {
	mock := &MockKYCRepository{ctrl: ctrl}
	mock.recorder = &MockKYCRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKYCRepository) EXPECT() *MockKYCRepositoryMockRecorder {
	return m.recorder
}

// ApproveKYCSubmission mocks base method.
func (m *MockKYCRepository) ApproveKYCSubmission(ctx context.Context, id uuid.UUID, decidedBy, providerRef, reason string, applyTier func(context.Context, uuid.UUID, int) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveKYCSubmission", ctx, id, decidedBy, providerRef, reason, applyTier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveKYCSubmission indicates an expected call of ApproveKYCSubmission.
func (mr *MockKYCRepositoryMockRecorder) ApproveKYCSubmission(ctx, id, decidedBy, providerRef, reason, applyTier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveKYCSubmission", reflect.TypeOf((*MockKYCRepository)(nil).ApproveKYCSubmission), ctx, id, decidedBy, providerRef, reason, applyTier)
}

// ClaimKYCApplyRetries mocks base method.
func (m *MockKYCRepository) ClaimKYCApplyRetries(ctx context.Context, limit int, lease time.Duration) ([]model.KYCApplyRetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimKYCApplyRetries", ctx, limit, lease)
	ret0, _ := ret[0].([]model.KYCApplyRetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimKYCApplyRetries indicates an expected call of ClaimKYCApplyRetries.
func (mr *MockKYCRepositoryMockRecorder) ClaimKYCApplyRetries(ctx, limit, lease any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimKYCApplyRetries", reflect.TypeOf((*MockKYCRepository)(nil).ClaimKYCApplyRetries), ctx, limit, lease)
}

// CreateKYCDocument mocks base method.
func (m *MockKYCRepository) CreateKYCDocument(arg0 context.Context, arg1 model.KYCDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKYCDocument", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKYCDocument indicates an expected call of CreateKYCDocument.
func (mr *MockKYCRepositoryMockRecorder) CreateKYCDocument(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKYCDocument", reflect.TypeOf((*MockKYCRepository)(nil).CreateKYCDocument), arg0, arg1)
}

// CreateKYCSubmission mocks base method.
func (m *MockKYCRepository) CreateKYCSubmission(ctx context.Context, s model.KYCSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKYCSubmission", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKYCSubmission indicates an expected call of CreateKYCSubmission.
func (mr *MockKYCRepositoryMockRecorder) CreateKYCSubmission(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKYCSubmission", reflect.TypeOf((*MockKYCRepository)(nil).CreateKYCSubmission), ctx, s)
}

// DowngradeKYCLevel mocks base method.
func (m *MockKYCRepository) DowngradeKYCLevel(ctx context.Context, userID uuid.UUID, level int, decidedBy, reason string, applyTier func(context.Context, uuid.UUID, int) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DowngradeKYCLevel", ctx, userID, level, decidedBy, reason, applyTier)
	ret0, _ := ret[0].(error)
	return ret0
}

// DowngradeKYCLevel indicates an expected call of DowngradeKYCLevel.
func (mr *MockKYCRepositoryMockRecorder) DowngradeKYCLevel(ctx, userID, level, decidedBy, reason, applyTier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DowngradeKYCLevel", reflect.TypeOf((*MockKYCRepository)(nil).DowngradeKYCLevel), ctx, userID, level, decidedBy, reason, applyTier)
}

// EnqueueKYCApplyRetry mocks base method.
func (m *MockKYCRepository) EnqueueKYCApplyRetry(ctx context.Context, retry model.KYCApplyRetry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueKYCApplyRetry", ctx, retry)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueKYCApplyRetry indicates an expected call of EnqueueKYCApplyRetry.
func (mr *MockKYCRepositoryMockRecorder) EnqueueKYCApplyRetry(ctx, retry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueKYCApplyRetry", reflect.TypeOf((*MockKYCRepository)(nil).EnqueueKYCApplyRetry), ctx, retry)
}

// GetKYCDocument mocks base method.
func (m *MockKYCRepository) GetKYCDocument(arg0 context.Context, arg1 uuid.UUID) (model.KYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKYCDocument", arg0, arg1)
	ret0, _ := ret[0].(model.KYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKYCDocument indicates an expected call of GetKYCDocument.
func (mr *MockKYCRepositoryMockRecorder) GetKYCDocument(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKYCDocument", reflect.TypeOf((*MockKYCRepository)(nil).GetKYCDocument), arg0, arg1)
}

// GetKYCSubmission mocks base method.
func (m *MockKYCRepository) GetKYCSubmission(ctx context.Context, id uuid.UUID) (model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKYCSubmission", ctx, id)
	ret0, _ := ret[0].(model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKYCSubmission indicates an expected call of GetKYCSubmission.
func (mr *MockKYCRepositoryMockRecorder) GetKYCSubmission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKYCSubmission", reflect.TypeOf((*MockKYCRepository)(nil).GetKYCSubmission), ctx, id)
}

// GetLatestKYCSubmission mocks base method.
func (m *MockKYCRepository) GetLatestKYCSubmission(ctx context.Context, userID uuid.UUID) (model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestKYCSubmission", ctx, userID)
	ret0, _ := ret[0].(model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestKYCSubmission indicates an expected call of GetLatestKYCSubmission.
func (mr *MockKYCRepositoryMockRecorder) GetLatestKYCSubmission(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestKYCSubmission", reflect.TypeOf((*MockKYCRepository)(nil).GetLatestKYCSubmission), ctx, userID)
}

// ListKYCSubmissions mocks base method.
func (m *MockKYCRepository) ListKYCSubmissions(ctx context.Context, status string) ([]model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKYCSubmissions", ctx, status)
	ret0, _ := ret[0].([]model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKYCSubmissions indicates an expected call of ListKYCSubmissions.
func (mr *MockKYCRepositoryMockRecorder) ListKYCSubmissions(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKYCSubmissions", reflect.TypeOf((*MockKYCRepository)(nil).ListKYCSubmissions), ctx, status)
}

// MarkKYCApplyRetryFailure mocks base method.
func (m *MockKYCRepository) MarkKYCApplyRetryFailure(ctx context.Context, id uuid.UUID, retryCount int, nextAttemptAt time.Time, lastError string, dead bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKYCApplyRetryFailure", ctx, id, retryCount, nextAttemptAt, lastError, dead)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkKYCApplyRetryFailure indicates an expected call of MarkKYCApplyRetryFailure.
func (mr *MockKYCRepositoryMockRecorder) MarkKYCApplyRetryFailure(ctx, id, retryCount, nextAttemptAt, lastError, dead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKYCApplyRetryFailure", reflect.TypeOf((*MockKYCRepository)(nil).MarkKYCApplyRetryFailure), ctx, id, retryCount, nextAttemptAt, lastError, dead)
}

// MarkKYCApplyRetrySucceeded mocks base method.
func (m *MockKYCRepository) MarkKYCApplyRetrySucceeded(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKYCApplyRetrySucceeded", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkKYCApplyRetrySucceeded indicates an expected call of MarkKYCApplyRetrySucceeded.
func (mr *MockKYCRepositoryMockRecorder) MarkKYCApplyRetrySucceeded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKYCApplyRetrySucceeded", reflect.TypeOf((*MockKYCRepository)(nil).MarkKYCApplyRetrySucceeded), ctx, id)
}

// RejectKYCSubmission mocks base method.
func (m *MockKYCRepository) RejectKYCSubmission(ctx context.Context, id uuid.UUID, decidedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectKYCSubmission", ctx, id, decidedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectKYCSubmission indicates an expected call of RejectKYCSubmission.
func (mr *MockKYCRepositoryMockRecorder) RejectKYCSubmission(ctx, id, decidedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectKYCSubmission", reflect.TypeOf((*MockKYCRepository)(nil).RejectKYCSubmission), ctx, id, decidedBy, reason)
}
