// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=refresh_token_repository.go -destination=refresh_token_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/auth/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// GetRefreshTokenByHash mocks base method.
func (m *MockRefreshTokenRepository) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByHash indicates an expected call of GetRefreshTokenByHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetRefreshTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetRefreshTokenByHash), ctx, tokenHash)
}

// InsertRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) InsertRefreshToken(ctx context.Context, t model.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshToken", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRefreshToken indicates an expected call of InsertRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) InsertRefreshToken(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).InsertRefreshToken), ctx, t)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeAllForUser), ctx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) RevokeRefreshToken(ctx context.Context, id uuid.UUID, replacedBy *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, id, replacedBy)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeRefreshToken(ctx, id, replacedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeRefreshToken), ctx, id, replacedBy)
}
