// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/auth/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApproveKYCSubmission mocks base method.
func (m *MockRepository) ApproveKYCSubmission(ctx context.Context, id uuid.UUID, decidedBy, providerRef, reason string, applyTier func(context.Context, uuid.UUID, int) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveKYCSubmission", ctx, id, decidedBy, providerRef, reason, applyTier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveKYCSubmission indicates an expected call of ApproveKYCSubmission.
func (mr *MockRepositoryMockRecorder) ApproveKYCSubmission(ctx, id, decidedBy, providerRef, reason, applyTier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveKYCSubmission", reflect.TypeOf((*MockRepository)(nil).ApproveKYCSubmission), ctx, id, decidedBy, providerRef, reason, applyTier)
}

// CreateKYCSubmission mocks base method.
func (m *MockRepository) CreateKYCSubmission(ctx context.Context, s model.KYCSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKYCSubmission", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKYCSubmission indicates an expected call of CreateKYCSubmission.
func (mr *MockRepositoryMockRecorder) CreateKYCSubmission(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKYCSubmission", reflect.TypeOf((*MockRepository)(nil).CreateKYCSubmission), ctx, s)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, u model.User, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, u, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, u, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, u, passwordHash)
}

// GetKYCSubmission mocks base method.
func (m *MockRepository) GetKYCSubmission(ctx context.Context, id uuid.UUID) (model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKYCSubmission", ctx, id)
	ret0, _ := ret[0].(model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKYCSubmission indicates an expected call of GetKYCSubmission.
func (mr *MockRepositoryMockRecorder) GetKYCSubmission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKYCSubmission", reflect.TypeOf((*MockRepository)(nil).GetKYCSubmission), ctx, id)
}

// GetLatestKYCSubmission mocks base method.
func (m *MockRepository) GetLatestKYCSubmission(ctx context.Context, userID uuid.UUID) (model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestKYCSubmission", ctx, userID)
	ret0, _ := ret[0].(model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestKYCSubmission indicates an expected call of GetLatestKYCSubmission.
func (mr *MockRepositoryMockRecorder) GetLatestKYCSubmission(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestKYCSubmission", reflect.TypeOf((*MockRepository)(nil).GetLatestKYCSubmission), ctx, userID)
}

// GetPasswordHash mocks base method.
func (m *MockRepository) GetPasswordHash(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordHash", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordHash indicates an expected call of GetPasswordHash.
func (mr *MockRepositoryMockRecorder) GetPasswordHash(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordHash", reflect.TypeOf((*MockRepository)(nil).GetPasswordHash), ctx, userID)
}

// GetRefreshTokenByHash mocks base method.
func (m *MockRepository) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByHash indicates an expected call of GetRefreshTokenByHash.
func (mr *MockRepositoryMockRecorder) GetRefreshTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByHash", reflect.TypeOf((*MockRepository)(nil).GetRefreshTokenByHash), ctx, tokenHash)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id uuid.UUID) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// InsertRefreshToken mocks base method.
func (m *MockRepository) InsertRefreshToken(ctx context.Context, t model.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshToken", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRefreshToken indicates an expected call of InsertRefreshToken.
func (mr *MockRepositoryMockRecorder) InsertRefreshToken(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshToken", reflect.TypeOf((*MockRepository)(nil).InsertRefreshToken), ctx, t)
}

// ListKYCSubmissions mocks base method.
func (m *MockRepository) ListKYCSubmissions(ctx context.Context, status string) ([]model.KYCSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKYCSubmissions", ctx, status)
	ret0, _ := ret[0].([]model.KYCSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKYCSubmissions indicates an expected call of ListKYCSubmissions.
func (mr *MockRepositoryMockRecorder) ListKYCSubmissions(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKYCSubmissions", reflect.TypeOf((*MockRepository)(nil).ListKYCSubmissions), ctx, status)
}

// RejectKYCSubmission mocks base method.
func (m *MockRepository) RejectKYCSubmission(ctx context.Context, id uuid.UUID, decidedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectKYCSubmission", ctx, id, decidedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectKYCSubmission indicates an expected call of RejectKYCSubmission.
func (mr *MockRepositoryMockRecorder) RejectKYCSubmission(ctx, id, decidedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectKYCSubmission", reflect.TypeOf((*MockRepository)(nil).RejectKYCSubmission), ctx, id, decidedBy, reason)
}

// RevokeAllForUser mocks base method.
func (m *MockRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRepositoryMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRepository)(nil).RevokeAllForUser), ctx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockRepository) RevokeRefreshToken(ctx context.Context, id uuid.UUID, replacedBy *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, id, replacedBy)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockRepositoryMockRecorder) RevokeRefreshToken(ctx, id, replacedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockRepository)(nil).RevokeRefreshToken), ctx, id, replacedBy)
}

// UpdateFullName mocks base method.
func (m *MockRepository) UpdateFullName(ctx context.Context, userID uuid.UUID, fullName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFullName", ctx, userID, fullName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFullName indicates an expected call of UpdateFullName.
func (mr *MockRepositoryMockRecorder) UpdateFullName(ctx, userID, fullName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFullName", reflect.TypeOf((*MockRepository)(nil).UpdateFullName), ctx, userID, fullName)
}
