apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seev-aws-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: seev
    seev.io/provider: aws
spec:
  project: default
  source:
    repoURL: https://github.com/herdifirdausss/seev.git
    targetRevision: main
    path: deploy/helm/seev
    helm:
      valueFiles:
        - values.yaml
        - values-aws-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: seev-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
