// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=transport
//

// Package transport is a generated GoMock package.
package transport

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	processors "github.com/herdifirdausss/seev/internal/ledger/processors"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApproveAdjustment mocks base method.
func (m *MockService) ApproveAdjustment(ctx context.Context, id uuid.UUID, approverID string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveAdjustment", ctx, id, approverID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveAdjustment indicates an expected call of ApproveAdjustment.
func (mr *MockServiceMockRecorder) ApproveAdjustment(ctx, id, approverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveAdjustment", reflect.TypeOf((*MockService)(nil).ApproveAdjustment), ctx, id, approverID)
}

// CanAccessAccount mocks base method.
func (m *MockService) CanAccessAccount(ctx context.Context, accountID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessAccount", ctx, accountID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessAccount indicates an expected call of CanAccessAccount.
func (mr *MockServiceMockRecorder) CanAccessAccount(ctx, accountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessAccount", reflect.TypeOf((*MockService)(nil).CanAccessAccount), ctx, accountID, userID)
}

// CanAccessTransaction mocks base method.
func (m *MockService) CanAccessTransaction(ctx context.Context, txID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessTransaction", ctx, txID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessTransaction indicates an expected call of CanAccessTransaction.
func (mr *MockServiceMockRecorder) CanAccessTransaction(ctx, txID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessTransaction", reflect.TypeOf((*MockService)(nil).CanAccessTransaction), ctx, txID, userID)
}

// CancelSchedule mocks base method.
func (m *MockService) CancelSchedule(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSchedule", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSchedule indicates an expected call of CancelSchedule.
func (mr *MockServiceMockRecorder) CancelSchedule(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSchedule", reflect.TypeOf((*MockService)(nil).CancelSchedule), ctx, id, userID)
}

// CreateAdjustment mocks base method.
func (m *MockService) CreateAdjustment(ctx context.Context, requestedBy, adjType string, amount decimal.Decimal, targetUserID uuid.UUID, metadata map[string]any, reason string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdjustment", ctx, requestedBy, adjType, amount, targetUserID, metadata, reason)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdjustment indicates an expected call of CreateAdjustment.
func (mr *MockServiceMockRecorder) CreateAdjustment(ctx, requestedBy, adjType, amount, targetUserID, metadata, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdjustment", reflect.TypeOf((*MockService)(nil).CreateAdjustment), ctx, requestedBy, adjType, amount, targetUserID, metadata, reason)
}

// CreatePocket mocks base method.
func (m *MockService) CreatePocket(ctx context.Context, userID uuid.UUID, currency, pocketCode string) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePocket", ctx, userID, currency, pocketCode)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePocket indicates an expected call of CreatePocket.
func (mr *MockServiceMockRecorder) CreatePocket(ctx, userID, currency, pocketCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePocket", reflect.TypeOf((*MockService)(nil).CreatePocket), ctx, userID, currency, pocketCode)
}

// CreateSchedule mocks base method.
func (m *MockService) CreateSchedule(ctx context.Context, userID uuid.UUID, txType string, amount decimal.Decimal, targetUserID uuid.UUID, pocketCode string, metadata map[string]any, kind string, runAtDate time.Time, dayOfMonth *int, createdBy string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, userID, txType, amount, targetUserID, pocketCode, metadata, kind, runAtDate, dayOfMonth, createdBy)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockServiceMockRecorder) CreateSchedule(ctx, userID, txType, amount, targetUserID, pocketCode, metadata, kind, runAtDate, dayOfMonth, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockService)(nil).CreateSchedule), ctx, userID, txType, amount, targetUserID, pocketCode, metadata, kind, runAtDate, dayOfMonth, createdBy)
}

// GetAdjustment mocks base method.
func (m *MockService) GetAdjustment(ctx context.Context, id uuid.UUID) (model.PendingAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdjustment", ctx, id)
	ret0, _ := ret[0].(model.PendingAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdjustment indicates an expected call of GetAdjustment.
func (mr *MockServiceMockRecorder) GetAdjustment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdjustment", reflect.TypeOf((*MockService)(nil).GetAdjustment), ctx, id)
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(ctx context.Context, accountID uuid.UUID) (model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), ctx, accountID)
}

// GetBalanceAsOf mocks base method.
func (m *MockService) GetBalanceAsOf(ctx context.Context, accountID uuid.UUID, asOf time.Time) (model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceAsOf", ctx, accountID, asOf)
	ret0, _ := ret[0].(model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceAsOf indicates an expected call of GetBalanceAsOf.
func (mr *MockServiceMockRecorder) GetBalanceAsOf(ctx, accountID, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceAsOf", reflect.TypeOf((*MockService)(nil).GetBalanceAsOf), ctx, accountID, asOf)
}

// GetDailyMutationReport mocks base method.
func (m *MockService) GetDailyMutationReport(ctx context.Context, from, to time.Time) ([]model.ReportDailyMutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyMutationReport", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportDailyMutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyMutationReport indicates an expected call of GetDailyMutationReport.
func (mr *MockServiceMockRecorder) GetDailyMutationReport(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyMutationReport", reflect.TypeOf((*MockService)(nil).GetDailyMutationReport), ctx, from, to)
}

// GetDailyPositionReport mocks base method.
func (m *MockService) GetDailyPositionReport(ctx context.Context, from, to time.Time) ([]model.ReportDailyPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyPositionReport", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportDailyPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyPositionReport indicates an expected call of GetDailyPositionReport.
func (mr *MockServiceMockRecorder) GetDailyPositionReport(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyPositionReport", reflect.TypeOf((*MockService)(nil).GetDailyPositionReport), ctx, from, to)
}

// GetDisbursementReport mocks base method.
func (m *MockService) GetDisbursementReport(ctx context.Context, batchID uuid.UUID, status string, limit, offset int) (model.DisbursementBatchReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisbursementReport", ctx, batchID, status, limit, offset)
	ret0, _ := ret[0].(model.DisbursementBatchReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisbursementReport indicates an expected call of GetDisbursementReport.
func (mr *MockServiceMockRecorder) GetDisbursementReport(ctx, batchID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisbursementReport", reflect.TypeOf((*MockService)(nil).GetDisbursementReport), ctx, batchID, status, limit, offset)
}

// GetReconBatchReport mocks base method.
func (m *MockService) GetReconBatchReport(ctx context.Context, batchID uuid.UUID, matchStatus string, limit, offset int) (model.ReconBatchReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReconBatchReport", ctx, batchID, matchStatus, limit, offset)
	ret0, _ := ret[0].(model.ReconBatchReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReconBatchReport indicates an expected call of GetReconBatchReport.
func (mr *MockServiceMockRecorder) GetReconBatchReport(ctx, batchID, matchStatus, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReconBatchReport", reflect.TypeOf((*MockService)(nil).GetReconBatchReport), ctx, batchID, matchStatus, limit, offset)
}

// GetReconSummaryReport mocks base method.
func (m *MockService) GetReconSummaryReport(ctx context.Context, from, to time.Time) ([]model.ReportReconSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReconSummaryReport", ctx, from, to)
	ret0, _ := ret[0].([]model.ReportReconSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReconSummaryReport indicates an expected call of GetReconSummaryReport.
func (mr *MockServiceMockRecorder) GetReconSummaryReport(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReconSummaryReport", reflect.TypeOf((*MockService)(nil).GetReconSummaryReport), ctx, from, to)
}

// GetTransaction mocks base method.
func (m *MockService) GetTransaction(ctx context.Context, txID uuid.UUID) (model.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txID)
	ret0, _ := ret[0].(model.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockServiceMockRecorder) GetTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockService)(nil).GetTransaction), ctx, txID)
}

// GetUserCurrency mocks base method.
func (m *MockService) GetUserCurrency(ctx context.Context, userID uuid.UUID, pocketCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCurrency", ctx, userID, pocketCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCurrency indicates an expected call of GetUserCurrency.
func (mr *MockServiceMockRecorder) GetUserCurrency(ctx, userID, pocketCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCurrency", reflect.TypeOf((*MockService)(nil).GetUserCurrency), ctx, userID, pocketCode)
}

// ImportDisbursementBatch mocks base method.
func (m *MockService) ImportDisbursementBatch(ctx context.Context, filename string, rows []model.DisbursementImportRow, createdBy string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportDisbursementBatch", ctx, filename, rows, createdBy)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportDisbursementBatch indicates an expected call of ImportDisbursementBatch.
func (mr *MockServiceMockRecorder) ImportDisbursementBatch(ctx, filename, rows, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportDisbursementBatch", reflect.TypeOf((*MockService)(nil).ImportDisbursementBatch), ctx, filename, rows, createdBy)
}

// ImportReconBatch mocks base method.
func (m *MockService) ImportReconBatch(ctx context.Context, gateway string, reportDate time.Time, filename string, rows []model.ReconImportRow, createdBy string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportReconBatch", ctx, gateway, reportDate, filename, rows, createdBy)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportReconBatch indicates an expected call of ImportReconBatch.
func (mr *MockServiceMockRecorder) ImportReconBatch(ctx, gateway, reportDate, filename, rows, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportReconBatch", reflect.TypeOf((*MockService)(nil).ImportReconBatch), ctx, gateway, reportDate, filename, rows, createdBy)
}

// ListAccounts mocks base method.
func (m *MockService) ListAccounts(ctx context.Context, userID uuid.UUID) ([]model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, userID)
	ret0, _ := ret[0].([]model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockServiceMockRecorder) ListAccounts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockService)(nil).ListAccounts), ctx, userID)
}

// ListAdjustments mocks base method.
func (m *MockService) ListAdjustments(ctx context.Context, status string, limit int) ([]model.PendingAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdjustments", ctx, status, limit)
	ret0, _ := ret[0].([]model.PendingAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdjustments indicates an expected call of ListAdjustments.
func (mr *MockServiceMockRecorder) ListAdjustments(ctx, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdjustments", reflect.TypeOf((*MockService)(nil).ListAdjustments), ctx, status, limit)
}

// ListDeadOutboxEvents mocks base method.
func (m *MockService) ListDeadOutboxEvents(ctx context.Context, limit, offset int) ([]model.DeadOutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeadOutboxEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]model.DeadOutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeadOutboxEvents indicates an expected call of ListDeadOutboxEvents.
func (mr *MockServiceMockRecorder) ListDeadOutboxEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeadOutboxEvents", reflect.TypeOf((*MockService)(nil).ListDeadOutboxEvents), ctx, limit, offset)
}

// ListEntries mocks base method.
func (m *MockService) ListEntries(ctx context.Context, accountID uuid.UUID, beforeCreatedAt time.Time, beforeID uuid.UUID, limit int) ([]model.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, accountID, beforeCreatedAt, beforeID, limit)
	ret0, _ := ret[0].([]model.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockServiceMockRecorder) ListEntries(ctx, accountID, beforeCreatedAt, beforeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockService)(nil).ListEntries), ctx, accountID, beforeCreatedAt, beforeID, limit)
}

// ListReconBatches mocks base method.
func (m *MockService) ListReconBatches(ctx context.Context, limit, offset int) ([]model.ReconBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReconBatches", ctx, limit, offset)
	ret0, _ := ret[0].([]model.ReconBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReconBatches indicates an expected call of ListReconBatches.
func (mr *MockServiceMockRecorder) ListReconBatches(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReconBatches", reflect.TypeOf((*MockService)(nil).ListReconBatches), ctx, limit, offset)
}

// ListSavingsConfigs mocks base method.
func (m *MockService) ListSavingsConfigs(ctx context.Context) ([]model.SavingsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavingsConfigs", ctx)
	ret0, _ := ret[0].([]model.SavingsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSavingsConfigs indicates an expected call of ListSavingsConfigs.
func (mr *MockServiceMockRecorder) ListSavingsConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavingsConfigs", reflect.TypeOf((*MockService)(nil).ListSavingsConfigs), ctx)
}

// ListSchedules mocks base method.
func (m *MockService) ListSchedules(ctx context.Context, userID uuid.UUID) ([]model.ScheduledTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx, userID)
	ret0, _ := ret[0].([]model.ScheduledTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockServiceMockRecorder) ListSchedules(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockService)(nil).ListSchedules), ctx, userID)
}

// PauseSchedule mocks base method.
func (m *MockService) PauseSchedule(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSchedule", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSchedule indicates an expected call of PauseSchedule.
func (mr *MockServiceMockRecorder) PauseSchedule(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSchedule", reflect.TypeOf((*MockService)(nil).PauseSchedule), ctx, id, userID)
}

// Post mocks base method.
func (m *MockService) Post(ctx context.Context, cmd processors.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockServiceMockRecorder) Post(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockService)(nil).Post), ctx, cmd)
}

// ProvisionUser mocks base method.
func (m *MockService) ProvisionUser(ctx context.Context, userID uuid.UUID, currency string) ([]model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionUser", ctx, userID, currency)
	ret0, _ := ret[0].([]model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionUser indicates an expected call of ProvisionUser.
func (mr *MockServiceMockRecorder) ProvisionUser(ctx, userID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionUser", reflect.TypeOf((*MockService)(nil).ProvisionUser), ctx, userID, currency)
}

// RejectAdjustment mocks base method.
func (m *MockService) RejectAdjustment(ctx context.Context, id uuid.UUID, approverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectAdjustment", ctx, id, approverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectAdjustment indicates an expected call of RejectAdjustment.
func (mr *MockServiceMockRecorder) RejectAdjustment(ctx, id, approverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectAdjustment", reflect.TypeOf((*MockService)(nil).RejectAdjustment), ctx, id, approverID)
}

// ReplayDeadEvent mocks base method.
func (m *MockService) ReplayDeadEvent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDeadEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplayDeadEvent indicates an expected call of ReplayDeadEvent.
func (mr *MockServiceMockRecorder) ReplayDeadEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDeadEvent", reflect.TypeOf((*MockService)(nil).ReplayDeadEvent), ctx, id)
}

// ReplayDeadEvents mocks base method.
func (m *MockService) ReplayDeadEvents(ctx context.Context, olderThan time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDeadEvents", ctx, olderThan)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayDeadEvents indicates an expected call of ReplayDeadEvents.
func (mr *MockServiceMockRecorder) ReplayDeadEvents(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDeadEvents", reflect.TypeOf((*MockService)(nil).ReplayDeadEvents), ctx, olderThan)
}

// ResolveReconItem mocks base method.
func (m *MockService) ResolveReconItem(ctx context.Context, itemID uuid.UUID, requestedBy, adjType string, amount decimal.Decimal, reason string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReconItem", ctx, itemID, requestedBy, adjType, amount, reason)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveReconItem indicates an expected call of ResolveReconItem.
func (mr *MockServiceMockRecorder) ResolveReconItem(ctx, itemID, requestedBy, adjType, amount, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReconItem", reflect.TypeOf((*MockService)(nil).ResolveReconItem), ctx, itemID, requestedBy, adjType, amount, reason)
}

// ResumeSchedule mocks base method.
func (m *MockService) ResumeSchedule(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSchedule", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSchedule indicates an expected call of ResumeSchedule.
func (mr *MockServiceMockRecorder) ResumeSchedule(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSchedule", reflect.TypeOf((*MockService)(nil).ResumeSchedule), ctx, id, userID)
}

// RunDisbursement mocks base method.
func (m *MockService) RunDisbursement(ctx context.Context, batchID uuid.UUID, retryFailed bool) (model.DisbursementRunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunDisbursement", ctx, batchID, retryFailed)
	ret0, _ := ret[0].(model.DisbursementRunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunDisbursement indicates an expected call of RunDisbursement.
func (mr *MockServiceMockRecorder) RunDisbursement(ctx, batchID, retryFailed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDisbursement", reflect.TypeOf((*MockService)(nil).RunDisbursement), ctx, batchID, retryFailed)
}

// RunSchedulesNow mocks base method.
func (m *MockService) RunSchedulesNow(ctx context.Context, asOf time.Time) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSchedulesNow", ctx, asOf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RunSchedulesNow indicates an expected call of RunSchedulesNow.
func (mr *MockServiceMockRecorder) RunSchedulesNow(ctx, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSchedulesNow", reflect.TypeOf((*MockService)(nil).RunSchedulesNow), ctx, asOf)
}

// SetSavingsConfig mocks base method.
func (m *MockService) SetSavingsConfig(ctx context.Context, accountID uuid.UUID, annualRateBps int, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSavingsConfig", ctx, accountID, annualRateBps, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSavingsConfig indicates an expected call of SetSavingsConfig.
func (mr *MockServiceMockRecorder) SetSavingsConfig(ctx, accountID, annualRateBps, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSavingsConfig", reflect.TypeOf((*MockService)(nil).SetSavingsConfig), ctx, accountID, annualRateBps, enabled)
}

// Statement mocks base method.
func (m *MockService) Statement(ctx context.Context, accountID uuid.UUID, from, to time.Time) (model.Statement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statement", ctx, accountID, from, to)
	ret0, _ := ret[0].(model.Statement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Statement indicates an expected call of Statement.
func (mr *MockServiceMockRecorder) Statement(ctx, accountID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statement", reflect.TypeOf((*MockService)(nil).Statement), ctx, accountID, from, to)
}
