// Code generated by MockGen. DO NOT EDIT.
// Source: internal/payin/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/payin/repository/repository.go -destination=internal/payin/repository/repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/payin/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id uuid.UUID) (model.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetOrInsert mocks base method.
func (m *MockRepository) GetOrInsert(ctx context.Context, ev model.WebhookEvent) (model.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrInsert", ctx, ev)
	ret0, _ := ret[0].(model.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrInsert indicates an expected call of GetOrInsert.
func (mr *MockRepositoryMockRecorder) GetOrInsert(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrInsert", reflect.TypeOf((*MockRepository)(nil).GetOrInsert), ctx, ev)
}

// GetTopupIntent mocks base method.
func (m *MockRepository) GetTopupIntent(ctx context.Context, id uuid.UUID) (model.TopupIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopupIntent", ctx, id)
	ret0, _ := ret[0].(model.TopupIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopupIntent indicates an expected call of GetTopupIntent.
func (mr *MockRepositoryMockRecorder) GetTopupIntent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopupIntent", reflect.TypeOf((*MockRepository)(nil).GetTopupIntent), ctx, id)
}

// GetTopupIntentByReference mocks base method.
func (m *MockRepository) GetTopupIntentByReference(ctx context.Context, reference string) (model.TopupIntent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopupIntentByReference", ctx, reference)
	ret0, _ := ret[0].(model.TopupIntent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTopupIntentByReference indicates an expected call of GetTopupIntentByReference.
func (mr *MockRepositoryMockRecorder) GetTopupIntentByReference(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopupIntentByReference", reflect.TypeOf((*MockRepository)(nil).GetTopupIntentByReference), ctx, reference)
}

// InsertTopupIntent mocks base method.
func (m *MockRepository) InsertTopupIntent(ctx context.Context, intent model.TopupIntent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTopupIntent", ctx, intent)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTopupIntent indicates an expected call of InsertTopupIntent.
func (mr *MockRepositoryMockRecorder) InsertTopupIntent(ctx, intent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTopupIntent", reflect.TypeOf((*MockRepository)(nil).InsertTopupIntent), ctx, intent)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, vendor, status string, limit, offset int) ([]model.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, vendor, status, limit, offset)
	ret0, _ := ret[0].([]model.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, vendor, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, vendor, status, limit, offset)
}

// MarkBlocked mocks base method.
func (m *MockRepository) MarkBlocked(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBlocked", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBlocked indicates an expected call of MarkBlocked.
func (mr *MockRepositoryMockRecorder) MarkBlocked(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBlocked", reflect.TypeOf((*MockRepository)(nil).MarkBlocked), ctx, id, reason)
}

// MarkFailed mocks base method.
func (m *MockRepository) MarkFailed(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockRepositoryMockRecorder) MarkFailed(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockRepository)(nil).MarkFailed), ctx, id, reason)
}

// MarkPosted mocks base method.
func (m *MockRepository) MarkPosted(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPosted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPosted indicates an expected call of MarkPosted.
func (mr *MockRepositoryMockRecorder) MarkPosted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPosted", reflect.TypeOf((*MockRepository)(nil).MarkPosted), ctx, id)
}

// MarkTopupIntentExpired mocks base method.
func (m *MockRepository) MarkTopupIntentExpired(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTopupIntentExpired", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTopupIntentExpired indicates an expected call of MarkTopupIntentExpired.
func (mr *MockRepositoryMockRecorder) MarkTopupIntentExpired(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTopupIntentExpired", reflect.TypeOf((*MockRepository)(nil).MarkTopupIntentExpired), ctx, id)
}

// MarkTopupIntentSettled mocks base method.
func (m *MockRepository) MarkTopupIntentSettled(ctx context.Context, reference string, eventID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTopupIntentSettled", ctx, reference, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkTopupIntentSettled indicates an expected call of MarkTopupIntentSettled.
func (mr *MockRepositoryMockRecorder) MarkTopupIntentSettled(ctx, reference, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTopupIntentSettled", reflect.TypeOf((*MockRepository)(nil).MarkTopupIntentSettled), ctx, reference, eventID)
}
