// Code generated by MockGen. DO NOT EDIT.
// Source: processors.go
//
// Generated by this command:
//
//	mockgen -source=processors.go -destination=processors_mock.go -package=processors
//

// Package processors is a generated GoMock package.
package processors

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTxProcessor is a mock of TxProcessor interface.
type MockTxProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTxProcessorMockRecorder
	isgomock struct{}
}

// MockTxProcessorMockRecorder is the mock recorder for MockTxProcessor.
type MockTxProcessorMockRecorder struct {
	mock *MockTxProcessor
}

// NewMockTxProcessor creates a new mock instance.
func NewMockTxProcessor(ctrl *gomock.Controller) *MockTxProcessor {
	mock := &MockTxProcessor{ctrl: ctrl}
	mock.recorder = &MockTxProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxProcessor) EXPECT() *MockTxProcessorMockRecorder {
	return m.recorder
}

// AfterCommit mocks base method.
func (m *MockTxProcessor) AfterCommit(ctx context.Context, cmd Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterCommit", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterCommit indicates an expected call of AfterCommit.
func (mr *MockTxProcessorMockRecorder) AfterCommit(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterCommit", reflect.TypeOf((*MockTxProcessor)(nil).AfterCommit), ctx, cmd)
}

// BuildEntries mocks base method.
func (m *MockTxProcessor) BuildEntries(ctx context.Context, tx *sql.Tx, cmd ResolvedCommand, balances map[uuid.UUID]model.AccountBalance) ([]model.EntryInstruction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildEntries", ctx, tx, cmd, balances)
	ret0, _ := ret[0].([]model.EntryInstruction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildEntries indicates an expected call of BuildEntries.
func (mr *MockTxProcessorMockRecorder) BuildEntries(ctx, tx, cmd, balances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildEntries", reflect.TypeOf((*MockTxProcessor)(nil).BuildEntries), ctx, tx, cmd, balances)
}

// OutboxEvents mocks base method.
func (m *MockTxProcessor) OutboxEvents(cmd ResolvedCommand, txID uuid.UUID, entries []model.EntryInstruction) []model.OutboxEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxEvents", cmd, txID, entries)
	ret0, _ := ret[0].([]model.OutboxEvent)
	return ret0
}

// OutboxEvents indicates an expected call of OutboxEvents.
func (mr *MockTxProcessorMockRecorder) OutboxEvents(cmd, txID, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxEvents", reflect.TypeOf((*MockTxProcessor)(nil).OutboxEvents), cmd, txID, entries)
}

// ResolveAccounts mocks base method.
func (m *MockTxProcessor) ResolveAccounts(ctx context.Context, cmd Command) (ResolvedAccounts, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAccounts", ctx, cmd)
	ret0, _ := ret[0].(ResolvedAccounts)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveAccounts indicates an expected call of ResolveAccounts.
func (mr *MockTxProcessorMockRecorder) ResolveAccounts(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAccounts", reflect.TypeOf((*MockTxProcessor)(nil).ResolveAccounts), ctx, cmd)
}

// Type mocks base method.
func (m *MockTxProcessor) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockTxProcessorMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTxProcessor)(nil).Type))
}

// Validate mocks base method.
func (m *MockTxProcessor) Validate(ctx context.Context, tx *sql.Tx, cmd ResolvedCommand, balances map[uuid.UUID]model.AccountBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, tx, cmd, balances)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockTxProcessorMockRecorder) Validate(ctx, tx, cmd, balances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTxProcessor)(nil).Validate), ctx, tx, cmd, balances)
}

// ValidateCommand mocks base method.
func (m *MockTxProcessor) ValidateCommand(ctx context.Context, cmd Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCommand", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCommand indicates an expected call of ValidateCommand.
func (mr *MockTxProcessorMockRecorder) ValidateCommand(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCommand", reflect.TypeOf((*MockTxProcessor)(nil).ValidateCommand), ctx, cmd)
}
