apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-egress
  namespace: seev-observability
spec:
  podSelector: {matchLabels: {app.kubernetes.io/name: prometheus}}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: seev-app}}
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: seev-edge}}
      ports:
        - {protocol: TCP, port: 8081}
        - {protocol: TCP, port: 8083}
        - {protocol: TCP, port: 8091}
        - {protocol: TCP, port: 8092}
        - {protocol: TCP, port: 8093}
        - {protocol: TCP, port: 8094}
        - {protocol: TCP, port: 8095}
        - {protocol: TCP, port: 8096}
        - {protocol: TCP, port: 8098}
        - {protocol: TCP, port: 9100}
    - to:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-default-deny
  namespace: seev-observability
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
