apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: seev-app
spec:
  provider:
    gcpsm:
      projectID: REPLACE_WITH_GCP_PROJECT
      auth:
        workloadIdentity:
          clusterLocation: REPLACE_WITH_GKE_ZONE
          clusterName: REPLACE_WITH_GKE_CLUSTER
          serviceAccountRef:
            name: seev-secrets-reader
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seev-runtime-secrets
  namespace: seev-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: seev-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef: {key: REPLACE_WITH_RUNTIME_SECRET_OBJECT, property: jwt-secret}
    - secretKey: internal-grpc-token
      remoteRef: {key: REPLACE_WITH_RUNTIME_SECRET_OBJECT, property: internal-grpc-token}
