// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=policy
//

// Package policy is a generated GoMock package.
package policy

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetEffective mocks base method.
func (m *MockRepository) GetEffective(ctx context.Context, userID uuid.UUID, txType string) (Limit, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffective", ctx, userID, txType)
	ret0, _ := ret[0].(Limit)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEffective indicates an expected call of GetEffective.
func (mr *MockRepositoryMockRecorder) GetEffective(ctx, userID, txType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffective", reflect.TypeOf((*MockRepository)(nil).GetEffective), ctx, userID, txType)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, txType string, userID *uuid.UUID) ([]Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, txType, userID)
	ret0, _ := ret[0].([]Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, txType, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, txType, userID)
}

// Upsert mocks base method.
func (m *MockRepository) Upsert(ctx context.Context, l Limit) (Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, l)
	ret0, _ := ret[0].(Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRepositoryMockRecorder) Upsert(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRepository)(nil).Upsert), ctx, l)
}

// MockrowScanner is a mock of rowScanner interface.
type MockrowScanner struct {
	ctrl     *gomock.Controller
	recorder *MockrowScannerMockRecorder
	isgomock struct{}
}

// MockrowScannerMockRecorder is the mock recorder for MockrowScanner.
type MockrowScannerMockRecorder struct {
	mock *MockrowScanner
}

// NewMockrowScanner creates a new mock instance.
func NewMockrowScanner(ctrl *gomock.Controller) *MockrowScanner {
	mock := &MockrowScanner{ctrl: ctrl}
	mock.recorder = &MockrowScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrowScanner) EXPECT() *MockrowScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockrowScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockrowScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockrowScanner)(nil).Scan), dest...)
}
