-- docs/roadmap/archive/51-a8-data-lifecycle-privacy.md "A8 T2.5b" (contract migration):
-- drops the plaintext destination column now that the expand-phase
-- backfill has baked. Deliberately does NOT make destination_ciphertext/
-- destination_key_version NOT NULL — T2.6's own
-- fn_retention_purge_requests_destination_and_error legitimately NULLs
-- destination_ciphertext after 30 days (migrations/payout/000010), a
-- real "this row was redacted" state, not a bug — the column must stay
-- nullable. Application code (repository.go's scanRequest) now treats a
-- NULL ciphertext as "redacted" and returns the same {"redacted":true}
-- marker the retention function used to write into the plaintext column
-- directly.
ALTER TABLE payout_requests DROP COLUMN destination;
