// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/payout/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountStuck mocks base method.
func (m *MockRepository) CountStuck(ctx context.Context, statuses []string, olderThan time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountStuck", ctx, statuses, olderThan)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountStuck indicates an expected call of CountStuck.
func (mr *MockRepositoryMockRecorder) CountStuck(ctx, statuses, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStuck", reflect.TypeOf((*MockRepository)(nil).CountStuck), ctx, statuses, olderThan)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id uuid.UUID) (model.PayoutRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.PayoutRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// Insert mocks base method.
func (m *MockRepository) Insert(ctx context.Context, req model.PayoutRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRepositoryMockRecorder) Insert(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRepository)(nil).Insert), ctx, req)
}

// InsertVendorCall mocks base method.
func (m *MockRepository) InsertVendorCall(ctx context.Context, call model.PayoutVendorCall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVendorCall", ctx, call)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVendorCall indicates an expected call of InsertVendorCall.
func (mr *MockRepositoryMockRecorder) InsertVendorCall(ctx, call any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVendorCall", reflect.TypeOf((*MockRepository)(nil).InsertVendorCall), ctx, call)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, status, vendor string, limit, offset int) ([]model.PayoutRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, status, vendor, limit, offset)
	ret0, _ := ret[0].([]model.PayoutRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, status, vendor, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, status, vendor, limit, offset)
}

// ListStuck mocks base method.
func (m *MockRepository) ListStuck(ctx context.Context, status string, olderThan time.Time, limit int) ([]model.PayoutRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStuck", ctx, status, olderThan, limit)
	ret0, _ := ret[0].([]model.PayoutRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStuck indicates an expected call of ListStuck.
func (mr *MockRepositoryMockRecorder) ListStuck(ctx, status, olderThan, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStuck", reflect.TypeOf((*MockRepository)(nil).ListStuck), ctx, status, olderThan, limit)
}

// ListVendorCalls mocks base method.
func (m *MockRepository) ListVendorCalls(ctx context.Context, payoutRequestID uuid.UUID) ([]model.PayoutVendorCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVendorCalls", ctx, payoutRequestID)
	ret0, _ := ret[0].([]model.PayoutVendorCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVendorCalls indicates an expected call of ListVendorCalls.
func (mr *MockRepositoryMockRecorder) ListVendorCalls(ctx, payoutRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVendorCalls", reflect.TypeOf((*MockRepository)(nil).ListVendorCalls), ctx, payoutRequestID)
}

// SetError mocks base method.
func (m *MockRepository) SetError(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetError", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetError indicates an expected call of SetError.
func (mr *MockRepositoryMockRecorder) SetError(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetError", reflect.TypeOf((*MockRepository)(nil).SetError), ctx, id, reason)
}

// SetQuotedFee mocks base method.
func (m *MockRepository) SetQuotedFee(ctx context.Context, id, quoteID uuid.UUID, feeAmount decimal.Decimal, feeGateway string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetQuotedFee", ctx, id, quoteID, feeAmount, feeGateway)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetQuotedFee indicates an expected call of SetQuotedFee.
func (mr *MockRepositoryMockRecorder) SetQuotedFee(ctx, id, quoteID, feeAmount, feeGateway any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuotedFee", reflect.TypeOf((*MockRepository)(nil).SetQuotedFee), ctx, id, quoteID, feeAmount, feeGateway)
}

// SetVendor mocks base method.
func (m *MockRepository) SetVendor(ctx context.Context, id uuid.UUID, vendor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVendor", ctx, id, vendor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVendor indicates an expected call of SetVendor.
func (mr *MockRepositoryMockRecorder) SetVendor(ctx, id, vendor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVendor", reflect.TypeOf((*MockRepository)(nil).SetVendor), ctx, id, vendor)
}

// TransitionBackToSubmitted mocks base method.
func (m *MockRepository) TransitionBackToSubmitted(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionBackToSubmitted", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionBackToSubmitted indicates an expected call of TransitionBackToSubmitted.
func (mr *MockRepositoryMockRecorder) TransitionBackToSubmitted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionBackToSubmitted", reflect.TypeOf((*MockRepository)(nil).TransitionBackToSubmitted), ctx, id)
}

// TransitionToCancelled mocks base method.
func (m *MockRepository) TransitionToCancelled(ctx context.Context, id, settleTxID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToCancelled", ctx, id, settleTxID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToCancelled indicates an expected call of TransitionToCancelled.
func (mr *MockRepositoryMockRecorder) TransitionToCancelled(ctx, id, settleTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToCancelled", reflect.TypeOf((*MockRepository)(nil).TransitionToCancelled), ctx, id, settleTxID)
}

// TransitionToFailed mocks base method.
func (m *MockRepository) TransitionToFailed(ctx context.Context, id uuid.UUID, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToFailed", ctx, id, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToFailed indicates an expected call of TransitionToFailed.
func (mr *MockRepositoryMockRecorder) TransitionToFailed(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToFailed", reflect.TypeOf((*MockRepository)(nil).TransitionToFailed), ctx, id, reason)
}

// TransitionToHeld mocks base method.
func (m *MockRepository) TransitionToHeld(ctx context.Context, id, holdTxID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToHeld", ctx, id, holdTxID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToHeld indicates an expected call of TransitionToHeld.
func (mr *MockRepositoryMockRecorder) TransitionToHeld(ctx, id, holdTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToHeld", reflect.TypeOf((*MockRepository)(nil).TransitionToHeld), ctx, id, holdTxID)
}

// TransitionToRejected mocks base method.
func (m *MockRepository) TransitionToRejected(ctx context.Context, id uuid.UUID, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToRejected", ctx, id, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToRejected indicates an expected call of TransitionToRejected.
func (mr *MockRepositoryMockRecorder) TransitionToRejected(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToRejected", reflect.TypeOf((*MockRepository)(nil).TransitionToRejected), ctx, id, reason)
}

// TransitionToSettled mocks base method.
func (m *MockRepository) TransitionToSettled(ctx context.Context, id, settleTxID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToSettled", ctx, id, settleTxID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToSettled indicates an expected call of TransitionToSettled.
func (mr *MockRepositoryMockRecorder) TransitionToSettled(ctx, id, settleTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToSettled", reflect.TypeOf((*MockRepository)(nil).TransitionToSettled), ctx, id, settleTxID)
}

// TransitionToSubmitted mocks base method.
func (m *MockRepository) TransitionToSubmitted(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToSubmitted", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToSubmitted indicates an expected call of TransitionToSubmitted.
func (mr *MockRepositoryMockRecorder) TransitionToSubmitted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToSubmitted", reflect.TypeOf((*MockRepository)(nil).TransitionToSubmitted), ctx, id)
}

// TransitionToVendorPending mocks base method.
func (m *MockRepository) TransitionToVendorPending(ctx context.Context, id uuid.UUID, vendorRef string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionToVendorPending", ctx, id, vendorRef)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionToVendorPending indicates an expected call of TransitionToVendorPending.
func (mr *MockRepositoryMockRecorder) TransitionToVendorPending(ctx, id, vendorRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionToVendorPending", reflect.TypeOf((*MockRepository)(nil).TransitionToVendorPending), ctx, id, vendorRef)
}

// MockrowScanner is a mock of rowScanner interface.
type MockrowScanner struct {
	ctrl     *gomock.Controller
	recorder *MockrowScannerMockRecorder
	isgomock struct{}
}

// MockrowScannerMockRecorder is the mock recorder for MockrowScanner.
type MockrowScannerMockRecorder struct {
	mock *MockrowScanner
}

// NewMockrowScanner creates a new mock instance.
func NewMockrowScanner(ctrl *gomock.Controller) *MockrowScanner {
	mock := &MockrowScanner{ctrl: ctrl}
	mock.recorder = &MockrowScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrowScanner) EXPECT() *MockrowScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockrowScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockrowScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockrowScanner)(nil).Scan), dest...)
}
