// Code generated by MockGen. DO NOT EDIT.
// Source: vendor_command_repository.go
//
// Generated by this command:
//
//	mockgen -source=vendor_command_repository.go -destination=vendor_command_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/internal/payout/model"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorCommandRepository is a mock of VendorCommandRepository interface.
type MockVendorCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorCommandRepositoryMockRecorder is the mock recorder for MockVendorCommandRepository.
type MockVendorCommandRepositoryMockRecorder struct {
	mock *MockVendorCommandRepository
}

// NewMockVendorCommandRepository creates a new mock instance.
func NewMockVendorCommandRepository(ctrl *gomock.Controller) *MockVendorCommandRepository {
	mock := &MockVendorCommandRepository{ctrl: ctrl}
	mock.recorder = &MockVendorCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorCommandRepository) EXPECT() *MockVendorCommandRepositoryMockRecorder {
	return m.recorder
}

// ClaimFailedCommandsForRetry mocks base method.
func (m *MockVendorCommandRepository) ClaimFailedCommandsForRetry(ctx context.Context, limit int) ([]model.PayoutVendorCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimFailedCommandsForRetry", ctx, limit)
	ret0, _ := ret[0].([]model.PayoutVendorCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimFailedCommandsForRetry indicates an expected call of ClaimFailedCommandsForRetry.
func (mr *MockVendorCommandRepositoryMockRecorder) ClaimFailedCommandsForRetry(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimFailedCommandsForRetry", reflect.TypeOf((*MockVendorCommandRepository)(nil).ClaimFailedCommandsForRetry), ctx, limit)
}

// ClaimPendingCommands mocks base method.
func (m *MockVendorCommandRepository) ClaimPendingCommands(ctx context.Context, limit int) ([]model.PayoutVendorCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingCommands", ctx, limit)
	ret0, _ := ret[0].([]model.PayoutVendorCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingCommands indicates an expected call of ClaimPendingCommands.
func (mr *MockVendorCommandRepositoryMockRecorder) ClaimPendingCommands(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingCommands", reflect.TypeOf((*MockVendorCommandRepository)(nil).ClaimPendingCommands), ctx, limit)
}

// CompleteAndEnqueueFailover mocks base method.
func (m *MockVendorCommandRepository) CompleteAndEnqueueFailover(ctx context.Context, payoutRequestID, completingCommandID uuid.UUID, fromVendor, toVendor string, nextAttempt int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteAndEnqueueFailover", ctx, payoutRequestID, completingCommandID, fromVendor, toVendor, nextAttempt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteAndEnqueueFailover indicates an expected call of CompleteAndEnqueueFailover.
func (mr *MockVendorCommandRepositoryMockRecorder) CompleteAndEnqueueFailover(ctx, payoutRequestID, completingCommandID, fromVendor, toVendor, nextAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteAndEnqueueFailover", reflect.TypeOf((*MockVendorCommandRepository)(nil).CompleteAndEnqueueFailover), ctx, payoutRequestID, completingCommandID, fromVendor, toVendor, nextAttempt)
}

// CompleteCommand mocks base method.
func (m *MockVendorCommandRepository) CompleteCommand(ctx context.Context, commandID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCommand", ctx, commandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCommand indicates an expected call of CompleteCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) CompleteCommand(ctx, commandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).CompleteCommand), ctx, commandID)
}

// CountCommandsByStatuses mocks base method.
func (m *MockVendorCommandRepository) CountCommandsByStatuses(ctx context.Context, statuses []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCommandsByStatuses", ctx, statuses)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCommandsByStatuses indicates an expected call of CountCommandsByStatuses.
func (mr *MockVendorCommandRepositoryMockRecorder) CountCommandsByStatuses(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCommandsByStatuses", reflect.TypeOf((*MockVendorCommandRepository)(nil).CountCommandsByStatuses), ctx, statuses)
}

// EnqueueInitialSubmit mocks base method.
func (m *MockVendorCommandRepository) EnqueueInitialSubmit(ctx context.Context, payoutRequestID uuid.UUID, vendor string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueInitialSubmit", ctx, payoutRequestID, vendor)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueInitialSubmit indicates an expected call of EnqueueInitialSubmit.
func (mr *MockVendorCommandRepositoryMockRecorder) EnqueueInitialSubmit(ctx, payoutRequestID, vendor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueInitialSubmit", reflect.TypeOf((*MockVendorCommandRepository)(nil).EnqueueInitialSubmit), ctx, payoutRequestID, vendor)
}

// EnsureSubmitCommand mocks base method.
func (m *MockVendorCommandRepository) EnsureSubmitCommand(ctx context.Context, payoutRequestID uuid.UUID, vendor string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSubmitCommand", ctx, payoutRequestID, vendor)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSubmitCommand indicates an expected call of EnsureSubmitCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) EnsureSubmitCommand(ctx, payoutRequestID, vendor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSubmitCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).EnsureSubmitCommand), ctx, payoutRequestID, vendor)
}

// FailCommand mocks base method.
func (m *MockVendorCommandRepository) FailCommand(ctx context.Context, commandID uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailCommand", ctx, commandID, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailCommand indicates an expected call of FailCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) FailCommand(ctx, commandID, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).FailCommand), ctx, commandID, errMsg)
}

// GetLiveCommand mocks base method.
func (m *MockVendorCommandRepository) GetLiveCommand(ctx context.Context, payoutRequestID uuid.UUID) (model.PayoutVendorCommand, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiveCommand", ctx, payoutRequestID)
	ret0, _ := ret[0].(model.PayoutVendorCommand)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLiveCommand indicates an expected call of GetLiveCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) GetLiveCommand(ctx, payoutRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiveCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).GetLiveCommand), ctx, payoutRequestID)
}

// HasDeadCommand mocks base method.
func (m *MockVendorCommandRepository) HasDeadCommand(ctx context.Context, payoutRequestID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDeadCommand", ctx, payoutRequestID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasDeadCommand indicates an expected call of HasDeadCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) HasDeadCommand(ctx, payoutRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDeadCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).HasDeadCommand), ctx, payoutRequestID)
}

// ListTriedVendors mocks base method.
func (m *MockVendorCommandRepository) ListTriedVendors(ctx context.Context, payoutRequestID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTriedVendors", ctx, payoutRequestID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTriedVendors indicates an expected call of ListTriedVendors.
func (mr *MockVendorCommandRepositoryMockRecorder) ListTriedVendors(ctx, payoutRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTriedVendors", reflect.TypeOf((*MockVendorCommandRepository)(nil).ListTriedVendors), ctx, payoutRequestID)
}

// ReapStuckCommands mocks base method.
func (m *MockVendorCommandRepository) ReapStuckCommands(ctx context.Context, olderThan time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReapStuckCommands", ctx, olderThan)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReapStuckCommands indicates an expected call of ReapStuckCommands.
func (mr *MockVendorCommandRepositoryMockRecorder) ReapStuckCommands(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReapStuckCommands", reflect.TypeOf((*MockVendorCommandRepository)(nil).ReapStuckCommands), ctx, olderThan)
}

// ReplayAllDeadCommands mocks base method.
func (m *MockVendorCommandRepository) ReplayAllDeadCommands(ctx context.Context, olderThan time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayAllDeadCommands", ctx, olderThan)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayAllDeadCommands indicates an expected call of ReplayAllDeadCommands.
func (mr *MockVendorCommandRepositoryMockRecorder) ReplayAllDeadCommands(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayAllDeadCommands", reflect.TypeOf((*MockVendorCommandRepository)(nil).ReplayAllDeadCommands), ctx, olderThan)
}

// ReplayDeadCommand mocks base method.
func (m *MockVendorCommandRepository) ReplayDeadCommand(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDeadCommand", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplayDeadCommand indicates an expected call of ReplayDeadCommand.
func (mr *MockVendorCommandRepositoryMockRecorder) ReplayDeadCommand(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDeadCommand", reflect.TypeOf((*MockVendorCommandRepository)(nil).ReplayDeadCommand), ctx, id)
}
