// Code generated by MockGen. DO NOT EDIT.
// Source: sanctions_repository.go
//
// Generated by this command:
//
//	mockgen -source=sanctions_repository.go -destination=sanctions_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSanctionsRepository is a mock of SanctionsRepository interface.
type MockSanctionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSanctionsRepositoryMockRecorder
	isgomock struct{}
}

// MockSanctionsRepositoryMockRecorder is the mock recorder for MockSanctionsRepository.
type MockSanctionsRepositoryMockRecorder struct {
	mock *MockSanctionsRepository
}

// NewMockSanctionsRepository creates a new mock instance.
func NewMockSanctionsRepository(ctrl *gomock.Controller) *MockSanctionsRepository {
	mock := &MockSanctionsRepository{ctrl: ctrl}
	mock.recorder = &MockSanctionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSanctionsRepository) EXPECT() *MockSanctionsRepositoryMockRecorder {
	return m.recorder
}

// MatchSanctions mocks base method.
func (m *MockSanctionsRepository) MatchSanctions(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchSanctions", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchSanctions indicates an expected call of MatchSanctions.
func (mr *MockSanctionsRepositoryMockRecorder) MatchSanctions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchSanctions", reflect.TypeOf((*MockSanctionsRepository)(nil).MatchSanctions), arg0, arg1, arg2)
}

// ReplaceSanctions mocks base method.
func (m *MockSanctionsRepository) ReplaceSanctions(arg0 context.Context, arg1 []SanctionsEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSanctions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSanctions indicates an expected call of ReplaceSanctions.
func (mr *MockSanctionsRepositoryMockRecorder) ReplaceSanctions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSanctions", reflect.TypeOf((*MockSanctionsRepository)(nil).ReplaceSanctions), arg0, arg1)
}
