// Code generated by MockGen. DO NOT EDIT.
// Source: screening_repository.go
//
// Generated by this command:
//
//	mockgen -source=screening_repository.go -destination=screening_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/seev/internal/fraud/model"
	gomock "go.uber.org/mock/gomock"
)

// MockScreeningRepository is a mock of ScreeningRepository interface.
type MockScreeningRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScreeningRepositoryMockRecorder
	isgomock struct{}
}

// MockScreeningRepositoryMockRecorder is the mock recorder for MockScreeningRepository.
type MockScreeningRepositoryMockRecorder struct {
	mock *MockScreeningRepository
}

// NewMockScreeningRepository creates a new mock instance.
func NewMockScreeningRepository(ctrl *gomock.Controller) *MockScreeningRepository {
	mock := &MockScreeningRepository{ctrl: ctrl}
	mock.recorder = &MockScreeningRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreeningRepository) EXPECT() *MockScreeningRepositoryMockRecorder {
	return m.recorder
}

// InsertEvent mocks base method.
func (m *MockScreeningRepository) InsertEvent(arg0 context.Context, arg1 model.ScreeningEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockScreeningRepositoryMockRecorder) InsertEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockScreeningRepository)(nil).InsertEvent), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockScreeningRepository) ListEvents(ctx context.Context, userID, verdict string, limit, offset int) ([]model.ScreeningEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, userID, verdict, limit, offset)
	ret0, _ := ret[0].([]model.ScreeningEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockScreeningRepositoryMockRecorder) ListEvents(ctx, userID, verdict, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockScreeningRepository)(nil).ListEvents), ctx, userID, verdict, limit, offset)
}
