// Code generated by MockGen. DO NOT EDIT.
// Source: interest_repository.go
//
// Generated by this command:
//
//	mockgen -source=interest_repository.go -destination=interest_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/services/ledger/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInterestRepository is a mock of InterestRepository interface.
type MockInterestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInterestRepositoryMockRecorder
	isgomock struct{}
}

// MockInterestRepositoryMockRecorder is the mock recorder for MockInterestRepository.
type MockInterestRepositoryMockRecorder struct {
	mock *MockInterestRepository
}

// NewMockInterestRepository creates a new mock instance.
func NewMockInterestRepository(ctrl *gomock.Controller) *MockInterestRepository {
	mock := &MockInterestRepository{ctrl: ctrl}
	mock.recorder = &MockInterestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterestRepository) EXPECT() *MockInterestRepositoryMockRecorder {
	return m.recorder
}

// ApproveAdjustment mocks base method.
func (m *MockInterestRepository) ApproveAdjustment(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveAdjustment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveAdjustment indicates an expected call of ApproveAdjustment.
func (mr *MockInterestRepositoryMockRecorder) ApproveAdjustment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveAdjustment", reflect.TypeOf((*MockInterestRepository)(nil).ApproveAdjustment), arg0, arg1, arg2)
}

// ApproveRate mocks base method.
func (m *MockInterestRepository) ApproveRate(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveRate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveRate indicates an expected call of ApproveRate.
func (mr *MockInterestRepositoryMockRecorder) ApproveRate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveRate", reflect.TypeOf((*MockInterestRepository)(nil).ApproveRate), arg0, arg1, arg2)
}

// ClaimDailyAccrual mocks base method.
func (m *MockInterestRepository) ClaimDailyAccrual(arg0 context.Context, arg1 string, arg2 time.Time) (model.InterestDailyAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDailyAccrual", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.InterestDailyAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDailyAccrual indicates an expected call of ClaimDailyAccrual.
func (mr *MockInterestRepositoryMockRecorder) ClaimDailyAccrual(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDailyAccrual", reflect.TypeOf((*MockInterestRepository)(nil).ClaimDailyAccrual), arg0, arg1, arg2)
}

// ClaimDailyAccrualForID mocks base method.
func (m *MockInterestRepository) ClaimDailyAccrualForID(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 time.Time) (model.InterestDailyAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDailyAccrualForID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.InterestDailyAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDailyAccrualForID indicates an expected call of ClaimDailyAccrualForID.
func (mr *MockInterestRepositoryMockRecorder) ClaimDailyAccrualForID(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDailyAccrualForID", reflect.TypeOf((*MockInterestRepository)(nil).ClaimDailyAccrualForID), arg0, arg1, arg2, arg3)
}

// CompleteCapitalization mocks base method.
func (m *MockInterestRepository) CompleteCapitalization(arg0 context.Context, arg1 *sql.Tx, arg2 uuid.UUID, arg3 string, arg4 *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCapitalization", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCapitalization indicates an expected call of CompleteCapitalization.
func (mr *MockInterestRepositoryMockRecorder) CompleteCapitalization(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCapitalization", reflect.TypeOf((*MockInterestRepository)(nil).CompleteCapitalization), arg0, arg1, arg2, arg3, arg4)
}

// CompleteDailyAccrual mocks base method.
func (m *MockInterestRepository) CompleteDailyAccrual(arg0 context.Context, arg1 *sql.Tx, arg2 uuid.UUID, arg3 string, arg4 *uuid.UUID, arg5, arg6 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteDailyAccrual", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteDailyAccrual indicates an expected call of CompleteDailyAccrual.
func (mr *MockInterestRepositoryMockRecorder) CompleteDailyAccrual(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteDailyAccrual", reflect.TypeOf((*MockInterestRepository)(nil).CompleteDailyAccrual), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// CountEligibleEnrollments mocks base method.
func (m *MockInterestRepository) CountEligibleEnrollments(arg0 context.Context, arg1 uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEligibleEnrollments", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEligibleEnrollments indicates an expected call of CountEligibleEnrollments.
func (mr *MockInterestRepositoryMockRecorder) CountEligibleEnrollments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEligibleEnrollments", reflect.TypeOf((*MockInterestRepository)(nil).CountEligibleEnrollments), arg0, arg1)
}

// CreateAdjustment mocks base method.
func (m *MockInterestRepository) CreateAdjustment(arg0 context.Context, arg1 model.InterestAdjustment) (model.InterestAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdjustment", arg0, arg1)
	ret0, _ := ret[0].(model.InterestAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdjustment indicates an expected call of CreateAdjustment.
func (mr *MockInterestRepositoryMockRecorder) CreateAdjustment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdjustment", reflect.TypeOf((*MockInterestRepository)(nil).CreateAdjustment), arg0, arg1)
}

// CreateEnrollment mocks base method.
func (m *MockInterestRepository) CreateEnrollment(arg0 context.Context, arg1 model.SavingsEnrollment) (model.SavingsEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnrollment", arg0, arg1)
	ret0, _ := ret[0].(model.SavingsEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnrollment indicates an expected call of CreateEnrollment.
func (mr *MockInterestRepositoryMockRecorder) CreateEnrollment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnrollment", reflect.TypeOf((*MockInterestRepository)(nil).CreateEnrollment), arg0, arg1)
}

// CreateOrGetDailyAccrual mocks base method.
func (m *MockInterestRepository) CreateOrGetDailyAccrual(arg0 context.Context, arg1 model.InterestDailyAccrual) (model.InterestDailyAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrGetDailyAccrual", arg0, arg1)
	ret0, _ := ret[0].(model.InterestDailyAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrGetDailyAccrual indicates an expected call of CreateOrGetDailyAccrual.
func (mr *MockInterestRepositoryMockRecorder) CreateOrGetDailyAccrual(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrGetDailyAccrual", reflect.TypeOf((*MockInterestRepository)(nil).CreateOrGetDailyAccrual), arg0, arg1)
}

// CreateProduct mocks base method.
func (m *MockInterestRepository) CreateProduct(arg0 context.Context, arg1 model.SavingsProduct) (model.SavingsProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(model.SavingsProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockInterestRepositoryMockRecorder) CreateProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockInterestRepository)(nil).CreateProduct), arg0, arg1)
}

// CreateRate mocks base method.
func (m *MockInterestRepository) CreateRate(arg0 context.Context, arg1 model.SavingsRateVersion) (model.SavingsRateVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRate", arg0, arg1)
	ret0, _ := ret[0].(model.SavingsRateVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRate indicates an expected call of CreateRate.
func (mr *MockInterestRepositoryMockRecorder) CreateRate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRate", reflect.TypeOf((*MockInterestRepository)(nil).CreateRate), arg0, arg1)
}

// EnsureCapitalizationItems mocks base method.
func (m *MockInterestRepository) EnsureCapitalizationItems(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCapitalizationItems", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureCapitalizationItems indicates an expected call of EnsureCapitalizationItems.
func (mr *MockInterestRepositoryMockRecorder) EnsureCapitalizationItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCapitalizationItems", reflect.TypeOf((*MockInterestRepository)(nil).EnsureCapitalizationItems), arg0, arg1)
}

// EnsurePeriod mocks base method.
func (m *MockInterestRepository) EnsurePeriod(arg0 context.Context, arg1 model.InterestPeriod) (model.InterestPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePeriod", arg0, arg1)
	ret0, _ := ret[0].(model.InterestPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePeriod indicates an expected call of EnsurePeriod.
func (mr *MockInterestRepositoryMockRecorder) EnsurePeriod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePeriod", reflect.TypeOf((*MockInterestRepository)(nil).EnsurePeriod), arg0, arg1)
}

// FailCapitalization mocks base method.
func (m *MockInterestRepository) FailCapitalization(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailCapitalization", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailCapitalization indicates an expected call of FailCapitalization.
func (mr *MockInterestRepositoryMockRecorder) FailCapitalization(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailCapitalization", reflect.TypeOf((*MockInterestRepository)(nil).FailCapitalization), arg0, arg1, arg2, arg3, arg4)
}

// FailDailyAccrual mocks base method.
func (m *MockInterestRepository) FailDailyAccrual(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailDailyAccrual", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailDailyAccrual indicates an expected call of FailDailyAccrual.
func (mr *MockInterestRepositoryMockRecorder) FailDailyAccrual(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailDailyAccrual", reflect.TypeOf((*MockInterestRepository)(nil).FailDailyAccrual), arg0, arg1, arg2, arg3, arg4)
}

// GetAdjustment mocks base method.
func (m *MockInterestRepository) GetAdjustment(arg0 context.Context, arg1 uuid.UUID) (model.InterestAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdjustment", arg0, arg1)
	ret0, _ := ret[0].(model.InterestAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdjustment indicates an expected call of GetAdjustment.
func (mr *MockInterestRepositoryMockRecorder) GetAdjustment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdjustment", reflect.TypeOf((*MockInterestRepository)(nil).GetAdjustment), arg0, arg1)
}

// GetCarryBeforeDate mocks base method.
func (m *MockInterestRepository) GetCarryBeforeDate(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarryBeforeDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetCarryBeforeDate indicates an expected call of GetCarryBeforeDate.
func (mr *MockInterestRepositoryMockRecorder) GetCarryBeforeDate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarryBeforeDate", reflect.TypeOf((*MockInterestRepository)(nil).GetCarryBeforeDate), arg0, arg1, arg2)
}

// GetEnrollment mocks base method.
func (m *MockInterestRepository) GetEnrollment(arg0 context.Context, arg1 uuid.UUID) (model.SavingsEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollment", arg0, arg1)
	ret0, _ := ret[0].(model.SavingsEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrollment indicates an expected call of GetEnrollment.
func (mr *MockInterestRepositoryMockRecorder) GetEnrollment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollment", reflect.TypeOf((*MockInterestRepository)(nil).GetEnrollment), arg0, arg1)
}

// GetPeriod mocks base method.
func (m *MockInterestRepository) GetPeriod(arg0 context.Context, arg1 uuid.UUID) (model.InterestPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeriod", arg0, arg1)
	ret0, _ := ret[0].(model.InterestPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeriod indicates an expected call of GetPeriod.
func (mr *MockInterestRepositoryMockRecorder) GetPeriod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeriod", reflect.TypeOf((*MockInterestRepository)(nil).GetPeriod), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockInterestRepository) GetProduct(arg0 context.Context, arg1 uuid.UUID) (model.SavingsProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(model.SavingsProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockInterestRepositoryMockRecorder) GetProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockInterestRepository)(nil).GetProduct), arg0, arg1)
}

// GetRateForDate mocks base method.
func (m *MockInterestRepository) GetRateForDate(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) (model.SavingsRateVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateForDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.SavingsRateVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateForDate indicates an expected call of GetRateForDate.
func (mr *MockInterestRepositoryMockRecorder) GetRateForDate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateForDate", reflect.TypeOf((*MockInterestRepository)(nil).GetRateForDate), arg0, arg1, arg2)
}

// HasNonActiveCapitalizationAccount mocks base method.
func (m *MockInterestRepository) HasNonActiveCapitalizationAccount(arg0 context.Context, arg1 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonActiveCapitalizationAccount", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonActiveCapitalizationAccount indicates an expected call of HasNonActiveCapitalizationAccount.
func (mr *MockInterestRepositoryMockRecorder) HasNonActiveCapitalizationAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonActiveCapitalizationAccount", reflect.TypeOf((*MockInterestRepository)(nil).HasNonActiveCapitalizationAccount), arg0, arg1)
}

// IsPreviousPeriodClosed mocks base method.
func (m *MockInterestRepository) IsPreviousPeriodClosed(arg0 context.Context, arg1 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPreviousPeriodClosed", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPreviousPeriodClosed indicates an expected call of IsPreviousPeriodClosed.
func (mr *MockInterestRepositoryMockRecorder) IsPreviousPeriodClosed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPreviousPeriodClosed", reflect.TypeOf((*MockInterestRepository)(nil).IsPreviousPeriodClosed), arg0, arg1)
}

// ListActiveEnrollments mocks base method.
func (m *MockInterestRepository) ListActiveEnrollments(arg0 context.Context, arg1 time.Time) ([]model.SavingsEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveEnrollments", arg0, arg1)
	ret0, _ := ret[0].([]model.SavingsEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveEnrollments indicates an expected call of ListActiveEnrollments.
func (mr *MockInterestRepositoryMockRecorder) ListActiveEnrollments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveEnrollments", reflect.TypeOf((*MockInterestRepository)(nil).ListActiveEnrollments), arg0, arg1)
}

// ListCapitalizationItems mocks base method.
func (m *MockInterestRepository) ListCapitalizationItems(arg0 context.Context, arg1 uuid.UUID) ([]model.InterestCapitalizationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCapitalizationItems", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestCapitalizationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCapitalizationItems indicates an expected call of ListCapitalizationItems.
func (mr *MockInterestRepositoryMockRecorder) ListCapitalizationItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCapitalizationItems", reflect.TypeOf((*MockInterestRepository)(nil).ListCapitalizationItems), arg0, arg1)
}

// ListDuePeriods mocks base method.
func (m *MockInterestRepository) ListDuePeriods(arg0 context.Context, arg1 time.Time) ([]model.InterestPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDuePeriods", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDuePeriods indicates an expected call of ListDuePeriods.
func (mr *MockInterestRepositoryMockRecorder) ListDuePeriods(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDuePeriods", reflect.TypeOf((*MockInterestRepository)(nil).ListDuePeriods), arg0, arg1)
}

// ListEnrollmentAccruals mocks base method.
func (m *MockInterestRepository) ListEnrollmentAccruals(arg0 context.Context, arg1 uuid.UUID) ([]model.InterestDailyAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnrollmentAccruals", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestDailyAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnrollmentAccruals indicates an expected call of ListEnrollmentAccruals.
func (mr *MockInterestRepositoryMockRecorder) ListEnrollmentAccruals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnrollmentAccruals", reflect.TypeOf((*MockInterestRepository)(nil).ListEnrollmentAccruals), arg0, arg1)
}

// ListEnrollmentCapitalizations mocks base method.
func (m *MockInterestRepository) ListEnrollmentCapitalizations(arg0 context.Context, arg1 uuid.UUID) ([]model.InterestCapitalizationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnrollmentCapitalizations", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestCapitalizationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnrollmentCapitalizations indicates an expected call of ListEnrollmentCapitalizations.
func (mr *MockInterestRepositoryMockRecorder) ListEnrollmentCapitalizations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnrollmentCapitalizations", reflect.TypeOf((*MockInterestRepository)(nil).ListEnrollmentCapitalizations), arg0, arg1)
}

// ListEnrollmentPeriods mocks base method.
func (m *MockInterestRepository) ListEnrollmentPeriods(arg0 context.Context, arg1 uuid.UUID) ([]model.InterestPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnrollmentPeriods", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnrollmentPeriods indicates an expected call of ListEnrollmentPeriods.
func (mr *MockInterestRepositoryMockRecorder) ListEnrollmentPeriods(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnrollmentPeriods", reflect.TypeOf((*MockInterestRepository)(nil).ListEnrollmentPeriods), arg0, arg1)
}

// ListEnrollments mocks base method.
func (m *MockInterestRepository) ListEnrollments(arg0 context.Context, arg1 uuid.UUID) ([]model.SavingsEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnrollments", arg0, arg1)
	ret0, _ := ret[0].([]model.SavingsEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnrollments indicates an expected call of ListEnrollments.
func (mr *MockInterestRepositoryMockRecorder) ListEnrollments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnrollments", reflect.TypeOf((*MockInterestRepository)(nil).ListEnrollments), arg0, arg1)
}

// ListPeriodAccruals mocks base method.
func (m *MockInterestRepository) ListPeriodAccruals(arg0 context.Context, arg1 uuid.UUID) ([]model.InterestDailyAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPeriodAccruals", arg0, arg1)
	ret0, _ := ret[0].([]model.InterestDailyAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPeriodAccruals indicates an expected call of ListPeriodAccruals.
func (mr *MockInterestRepositoryMockRecorder) ListPeriodAccruals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPeriodAccruals", reflect.TypeOf((*MockInterestRepository)(nil).ListPeriodAccruals), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockInterestRepository) ListProducts(arg0 context.Context, arg1 string) ([]model.SavingsProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].([]model.SavingsProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockInterestRepositoryMockRecorder) ListProducts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockInterestRepository)(nil).ListProducts), arg0, arg1)
}

// MarkAdjustmentPosted mocks base method.
func (m *MockInterestRepository) MarkAdjustmentPosted(arg0 context.Context, arg1 uuid.UUID, arg2 *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAdjustmentPosted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAdjustmentPosted indicates an expected call of MarkAdjustmentPosted.
func (mr *MockInterestRepositoryMockRecorder) MarkAdjustmentPosted(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAdjustmentPosted", reflect.TypeOf((*MockInterestRepository)(nil).MarkAdjustmentPosted), arg0, arg1, arg2)
}

// MarkPeriodStatus mocks base method.
func (m *MockInterestRepository) MarkPeriodStatus(arg0 context.Context, arg1 *sql.Tx, arg2 uuid.UUID, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPeriodStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPeriodStatus indicates an expected call of MarkPeriodStatus.
func (mr *MockInterestRepositoryMockRecorder) MarkPeriodStatus(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPeriodStatus", reflect.TypeOf((*MockInterestRepository)(nil).MarkPeriodStatus), arg0, arg1, arg2, arg3, arg4)
}

// PutPeriodCheck mocks base method.
func (m *MockInterestRepository) PutPeriodCheck(arg0 context.Context, arg1 model.InterestPeriodCheck) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPeriodCheck", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPeriodCheck indicates an expected call of PutPeriodCheck.
func (mr *MockInterestRepositoryMockRecorder) PutPeriodCheck(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPeriodCheck", reflect.TypeOf((*MockInterestRepository)(nil).PutPeriodCheck), arg0, arg1)
}

// RefreshExpectedItemCount mocks base method.
func (m *MockInterestRepository) RefreshExpectedItemCount(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshExpectedItemCount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshExpectedItemCount indicates an expected call of RefreshExpectedItemCount.
func (mr *MockInterestRepositoryMockRecorder) RefreshExpectedItemCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshExpectedItemCount", reflect.TypeOf((*MockInterestRepository)(nil).RefreshExpectedItemCount), arg0, arg1)
}

// RejectRate mocks base method.
func (m *MockInterestRepository) RejectRate(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectRate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectRate indicates an expected call of RejectRate.
func (mr *MockInterestRepositoryMockRecorder) RejectRate(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectRate", reflect.TypeOf((*MockInterestRepository)(nil).RejectRate), arg0, arg1, arg2, arg3)
}

// SaveDailyCalculation mocks base method.
func (m *MockInterestRepository) SaveDailyCalculation(arg0 context.Context, arg1 *sql.Tx, arg2 model.InterestDailyAccrual) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDailyCalculation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDailyCalculation indicates an expected call of SaveDailyCalculation.
func (mr *MockInterestRepositoryMockRecorder) SaveDailyCalculation(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDailyCalculation", reflect.TypeOf((*MockInterestRepository)(nil).SaveDailyCalculation), arg0, arg1, arg2)
}

// StartCapitalization mocks base method.
func (m *MockInterestRepository) StartCapitalization(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 time.Time) (model.InterestCapitalizationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCapitalization", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.InterestCapitalizationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCapitalization indicates an expected call of StartCapitalization.
func (mr *MockInterestRepositoryMockRecorder) StartCapitalization(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCapitalization", reflect.TypeOf((*MockInterestRepository)(nil).StartCapitalization), arg0, arg1, arg2, arg3)
}

// SubmitRate mocks base method.
func (m *MockInterestRepository) SubmitRate(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitRate indicates an expected call of SubmitRate.
func (mr *MockInterestRepositoryMockRecorder) SubmitRate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRate", reflect.TypeOf((*MockInterestRepository)(nil).SubmitRate), arg0, arg1, arg2)
}

// UpdateProductStatus mocks base method.
func (m *MockInterestRepository) UpdateProductStatus(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStatus indicates an expected call of UpdateProductStatus.
func (mr *MockInterestRepositoryMockRecorder) UpdateProductStatus(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStatus", reflect.TypeOf((*MockInterestRepository)(nil).UpdateProductStatus), arg0, arg1, arg2, arg3)
}
