// Code generated by MockGen. DO NOT EDIT.
// Source: schedule_repository.go
//
// Generated by this command:
//
//	mockgen -source=schedule_repository.go -destination=scheduled_occurrence_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/herdifirdausss/seev/services/ledger/internal/ledger/model"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduledOccurrenceRepository is a mock of ScheduledOccurrenceRepository interface.
type MockScheduledOccurrenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledOccurrenceRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduledOccurrenceRepositoryMockRecorder is the mock recorder for MockScheduledOccurrenceRepository.
type MockScheduledOccurrenceRepositoryMockRecorder struct {
	mock *MockScheduledOccurrenceRepository
}

// NewMockScheduledOccurrenceRepository creates a new mock instance.
func NewMockScheduledOccurrenceRepository(ctrl *gomock.Controller) *MockScheduledOccurrenceRepository {
	mock := &MockScheduledOccurrenceRepository{ctrl: ctrl}
	mock.recorder = &MockScheduledOccurrenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledOccurrenceRepository) EXPECT() *MockScheduledOccurrenceRepositoryMockRecorder {
	return m.recorder
}

// BlockSchedule mocks base method.
func (m *MockScheduledOccurrenceRepository) BlockSchedule(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSchedule", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSchedule indicates an expected call of BlockSchedule.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) BlockSchedule(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSchedule", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).BlockSchedule), arg0, arg1, arg2)
}

// Claim mocks base method.
func (m *MockScheduledOccurrenceRepository) Claim(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 time.Time) (model.ScheduledOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.ScheduledOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) Claim(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).Claim), arg0, arg1, arg2, arg3)
}

// CreateOrGet mocks base method.
func (m *MockScheduledOccurrenceRepository) CreateOrGet(arg0 context.Context, arg1 model.ScheduledOccurrence) (model.ScheduledOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrGet", arg0, arg1)
	ret0, _ := ret[0].(model.ScheduledOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrGet indicates an expected call of CreateOrGet.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) CreateOrGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrGet", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).CreateOrGet), arg0, arg1)
}

// FinishAttempt mocks base method.
func (m *MockScheduledOccurrenceRepository) FinishAttempt(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time, arg3 string, arg4 bool, arg5 string, arg6 *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishAttempt", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishAttempt indicates an expected call of FinishAttempt.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) FinishAttempt(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishAttempt", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).FinishAttempt), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// Get mocks base method.
func (m *MockScheduledOccurrenceRepository) Get(arg0 context.Context, arg1 uuid.UUID) (model.ScheduledOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.ScheduledOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockScheduledOccurrenceRepository) List(arg0 context.Context, arg1, arg2 uuid.UUID, arg3, arg4 int) ([]model.ScheduledOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]model.ScheduledOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) List(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).List), arg0, arg1, arg2, arg3, arg4)
}

// ListAttempts mocks base method.
func (m *MockScheduledOccurrenceRepository) ListAttempts(arg0 context.Context, arg1 uuid.UUID) ([]model.ScheduledExecutionAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttempts", arg0, arg1)
	ret0, _ := ret[0].([]model.ScheduledExecutionAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttempts indicates an expected call of ListAttempts.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) ListAttempts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttempts", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).ListAttempts), arg0, arg1)
}

// RecordAttempt mocks base method.
func (m *MockScheduledOccurrenceRepository) RecordAttempt(arg0 context.Context, arg1 model.ScheduledExecutionAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAttempt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAttempt indicates an expected call of RecordAttempt.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) RecordAttempt(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAttempt", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).RecordAttempt), arg0, arg1)
}

// RecordScheduleBusinessFailure mocks base method.
func (m *MockScheduledOccurrenceRepository) RecordScheduleBusinessFailure(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordScheduleBusinessFailure", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordScheduleBusinessFailure indicates an expected call of RecordScheduleBusinessFailure.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) RecordScheduleBusinessFailure(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordScheduleBusinessFailure", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).RecordScheduleBusinessFailure), arg0, arg1, arg2, arg3)
}

// RecordScheduleSuccess mocks base method.
func (m *MockScheduledOccurrenceRepository) RecordScheduleSuccess(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordScheduleSuccess", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordScheduleSuccess indicates an expected call of RecordScheduleSuccess.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) RecordScheduleSuccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordScheduleSuccess", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).RecordScheduleSuccess), arg0, arg1)
}

// SetFee mocks base method.
func (m *MockScheduledOccurrenceRepository) SetFee(arg0 context.Context, arg1 uuid.UUID, arg2 int64, arg3 *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFee", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFee indicates an expected call of SetFee.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) SetFee(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFee", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).SetFee), arg0, arg1, arg2, arg3)
}

// SetScheduleLastPlanned mocks base method.
func (m *MockScheduledOccurrenceRepository) SetScheduleLastPlanned(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetScheduleLastPlanned", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetScheduleLastPlanned indicates an expected call of SetScheduleLastPlanned.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) SetScheduleLastPlanned(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetScheduleLastPlanned", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).SetScheduleLastPlanned), arg0, arg1, arg2)
}

// SetScheduleLastRun mocks base method.
func (m *MockScheduledOccurrenceRepository) SetScheduleLastRun(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetScheduleLastRun", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetScheduleLastRun indicates an expected call of SetScheduleLastRun.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) SetScheduleLastRun(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetScheduleLastRun", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).SetScheduleLastRun), arg0, arg1, arg2, arg3)
}

// SetStatus mocks base method.
func (m *MockScheduledOccurrenceRepository) SetStatus(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4 *time.Time, arg5 *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockScheduledOccurrenceRepositoryMockRecorder) SetStatus(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockScheduledOccurrenceRepository)(nil).SetStatus), arg0, arg1, arg2, arg3, arg4, arg5)
}
