// Code generated by MockGen. DO NOT EDIT.
// Source: snapshot_repository.go
//
// Generated by this command:
//
//	mockgen -source=snapshot_repository.go -destination=snapshot_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockSnapshotRepository is a mock of SnapshotRepository interface.
type MockSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockSnapshotRepositoryMockRecorder is the mock recorder for MockSnapshotRepository.
type MockSnapshotRepositoryMockRecorder struct {
	mock *MockSnapshotRepository
}

// NewMockSnapshotRepository creates a new mock instance.
func NewMockSnapshotRepository(ctrl *gomock.Controller) *MockSnapshotRepository {
	mock := &MockSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotRepository) EXPECT() *MockSnapshotRepositoryMockRecorder {
	return m.recorder
}

// BalanceAsOf mocks base method.
func (m *MockSnapshotRepository) BalanceAsOf(ctx context.Context, accountID uuid.UUID, date time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BalanceAsOf", ctx, accountID, date)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BalanceAsOf indicates an expected call of BalanceAsOf.
func (mr *MockSnapshotRepositoryMockRecorder) BalanceAsOf(ctx, accountID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BalanceAsOf", reflect.TypeOf((*MockSnapshotRepository)(nil).BalanceAsOf), ctx, accountID, date)
}

// GetLatestBefore mocks base method.
func (m *MockSnapshotRepository) GetLatestBefore(ctx context.Context, accountID uuid.UUID, date time.Time) (decimal.Decimal, time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBefore", ctx, accountID, date)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLatestBefore indicates an expected call of GetLatestBefore.
func (mr *MockSnapshotRepositoryMockRecorder) GetLatestBefore(ctx, accountID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBefore", reflect.TypeOf((*MockSnapshotRepository)(nil).GetLatestBefore), ctx, accountID, date)
}

// InsertForDate mocks base method.
func (m *MockSnapshotRepository) InsertForDate(ctx context.Context, date time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertForDate", ctx, date)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertForDate indicates an expected call of InsertForDate.
func (mr *MockSnapshotRepositoryMockRecorder) InsertForDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertForDate", reflect.TypeOf((*MockSnapshotRepository)(nil).InsertForDate), ctx, date)
}

// LatestSnapshotDate mocks base method.
func (m *MockSnapshotRepository) LatestSnapshotDate(ctx context.Context) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSnapshotDate", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LatestSnapshotDate indicates an expected call of LatestSnapshotDate.
func (mr *MockSnapshotRepositoryMockRecorder) LatestSnapshotDate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSnapshotDate", reflect.TypeOf((*MockSnapshotRepository)(nil).LatestSnapshotDate), ctx)
}

// VerifyDate mocks base method.
func (m *MockSnapshotRepository) VerifyDate(ctx context.Context, date time.Time) ([]BalanceMismatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDate", ctx, date)
	ret0, _ := ret[0].([]BalanceMismatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDate indicates an expected call of VerifyDate.
func (mr *MockSnapshotRepositoryMockRecorder) VerifyDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDate", reflect.TypeOf((*MockSnapshotRepository)(nil).VerifyDate), ctx, date)
}
