apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
  labels:
    app.kubernetes.io/part-of: seev
rules:
  - apiGroups: [""]
    resources: [configmaps, services, endpoints, secrets, nodes, namespaces]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses, gateways, httproutes, grpcroutes, referencegrants, backendtlspolicies]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses/status, gateways/status, httproutes/status, grpcroutes/status, backendtlspolicies/status]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [traefik.io]
    resources: [middlewares, middlewaretcps, ingressroutes, ingressroutetcps, ingressrouteudps, tlsoptions, tlsstores, serverstransports, serverstransporttcps, traefikservices]
    verbs: [get, list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik
  labels:
    app.kubernetes.io/part-of: seev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: seev-edge
