apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: seev-edge
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: REPLACE_WITH_AWS_EIP
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
